insert into item_styles(name, created_at) values('None', NOW());
insert into item_styles(name, created_at) values('Modern stil', NOW());
insert into item_styles(name, created_at) values('Märzen och wienerstil', NOW());
insert into item_styles(name, created_at) values('Dunkel', NOW());
insert into item_styles(name, created_at) values('Hefeweizen', NOW());
insert into item_styles(name, created_at) values('Pilsner - tysk stil', NOW());
insert into item_styles(name, created_at) values('Zwickel / keller- och landbier', NOW());
insert into item_styles(name, created_at) values('Dortmunder och helles', NOW());
insert into item_styles(name, created_at) values('India pale ale (IPA)', NOW());
insert into item_styles(name, created_at) values('Amerikansk pale ale (APA)', NOW());
insert into item_styles(name, created_at) values('Montilla', NOW());
insert into item_styles(name, created_at) values('Pilsner - tjeckisk stil', NOW());
insert into item_styles(name, created_at) values('Black IPA', NOW());
insert into item_styles(name, created_at) values('Tawny', NOW());
insert into item_styles(name, created_at) values('Amber ale', NOW());
insert into item_styles(name, created_at) values('Imperial porter och stout', NOW());
insert into item_styles(name, created_at) values('Imperial/Dubbel IPA', NOW());
insert into item_styles(name, created_at) values('Andra smaksatta viner & fruktviner', NOW());
insert into item_styles(name, created_at) values('Övrig syrlig öl', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Amerikansk pale ale (APA)', NOW());
insert into item_styles(name, created_at) values('Vintage', NOW());
insert into item_styles(name, created_at) values('Flamländsk röd och brun öl', NOW());
insert into item_styles(name, created_at) values('Torr porter och stout', NOW());
insert into item_styles(name, created_at) values('Schwarzbier', NOW());
insert into item_styles(name, created_at) values('Presentkartong 1 flaska', NOW());
insert into item_styles(name, created_at) values('Presentkartong 2 flaskor', NOW());
insert into item_styles(name, created_at) values('Presentpåse 1 flaska', NOW());
insert into item_styles(name, created_at) values('Lambic - frukt och bär', NOW());
insert into item_styles(name, created_at) values('Amontillado', NOW());
insert into item_styles(name, created_at) values('Internationell stil', NOW());
insert into item_styles(name, created_at) values('Mjöd', NOW());
insert into item_styles(name, created_at) values('Sangria', NOW());
insert into item_styles(name, created_at) values('Engelsk pale ale och bitter', NOW());
insert into item_styles(name, created_at) values('Bière de garde', NOW());
insert into item_styles(name, created_at) values('Dubbelbock', NOW());
insert into item_styles(name, created_at) values('Late bottled vintage (LBV)', NOW());
insert into item_styles(name, created_at) values('Brown ale', NOW());
insert into item_styles(name, created_at) values('Saison', NOW());
insert into item_styles(name, created_at) values('Belgisk ljus ale', NOW());
insert into item_styles(name, created_at) values('Berliner weisse', NOW());
insert into item_styles(name, created_at) values('Session IPA', NOW());
insert into item_styles(name, created_at) values('Ljus bocköl', NOW());
insert into item_styles(name, created_at) values('Strong ale', NOW());
insert into item_styles(name, created_at) values('California common', NOW());
insert into item_styles(name, created_at) values('Öl av flera typer/stilar', NOW());
insert into item_styles(name, created_at) values('Belgisk mörk ale', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Mörk lager', NOW());
insert into item_styles(name, created_at) values('Lambic - gueuze', NOW());
insert into item_styles(name, created_at) values('Barley wine', NOW());
insert into item_styles(name, created_at) values('Golden/Blond ale', NOW());
insert into item_styles(name, created_at) values('Witbier', NOW());
insert into item_styles(name, created_at) values('Ruby', NOW());
insert into item_styles(name, created_at) values('Kristallweizen', NOW());
insert into item_styles(name, created_at) values('Extra special bitter', NOW());
insert into item_styles(name, created_at) values('Trippel', NOW());
insert into item_styles(name, created_at) values('Annan sherry', NOW());
insert into item_styles(name, created_at) values('Presentkartong 6 flaskor', NOW());
insert into item_styles(name, created_at) values('Malmsey/malvasia', NOW());
insert into item_styles(name, created_at) values('Söt porter och stout', NOW());
insert into item_styles(name, created_at) values('Irländsk ale', NOW());
insert into item_styles(name, created_at) values('Sercial', NOW());
insert into item_styles(name, created_at) values('Manzanilla', NOW());
insert into item_styles(name, created_at) values('Cream sherry', NOW());
insert into item_styles(name, created_at) values('Dunkelweizen', NOW());
insert into item_styles(name, created_at) values('Starkare lager', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Ljus lager', NOW());
insert into item_styles(name, created_at) values('Old ale', NOW());
insert into item_styles(name, created_at) values('Champagneförslutare', NOW());
insert into item_styles(name, created_at) values('Dubbel', NOW());
insert into item_styles(name, created_at) values('Colheita', NOW());
insert into item_styles(name, created_at) values('Altbier', NOW());
insert into item_styles(name, created_at) values('Mild', NOW());
insert into item_styles(name, created_at) values('Alkoholfri India pale ale', NOW());
insert into item_styles(name, created_at) values('Presentpåse 2 flaskor', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Pilsner - tysk Stil', NOW());
insert into item_styles(name, created_at) values('Gose och lichtenhainer', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Witbier', NOW());
insert into item_styles(name, created_at) values('Skotsk ale', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Mellanmörk lager', NOW());
insert into item_styles(name, created_at) values('Imperial pils och india pale lager (IPL)', NOW());
insert into item_styles(name, created_at) values('Hopfenweizen', NOW());
insert into item_styles(name, created_at) values('Pedro ximénez (PX)', NOW());
insert into item_styles(name, created_at) values('Verdelho', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Övrig syrlig öl', NOW());
insert into item_styles(name, created_at) values('Fino', NOW());
insert into item_styles(name, created_at) values('Abt och kvadrupel', NOW());
insert into item_styles(name, created_at) values('Polotmavý', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Torr porter och stout', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Engelsk pale ale och bitter', NOW());
insert into item_styles(name, created_at) values('Kölsch', NOW());
insert into item_styles(name, created_at) values('Annan madeira', NOW());
insert into item_styles(name, created_at) values('Vitt portvin', NOW());
insert into item_styles(name, created_at) values('Annat rött portvin', NOW());
insert into item_styles(name, created_at) values('Bual/boal', NOW());
insert into item_styles(name, created_at) values('Oloroso', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Lambic - frukt och bär', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Strong ale', NOW());
insert into item_styles(name, created_at) values('Förpackningsdekoration', NOW());
insert into item_styles(name, created_at) values('Weizenbock', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Hefeweizen', NOW());
insert into item_styles(name, created_at) values('Champagnekylare', NOW());
insert into item_styles(name, created_at) values('Vinkylare', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Zwickel, keller- och landbier', NOW());
insert into item_styles(name, created_at) values('Palo cortado', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Internationell stil', NOW());
insert into item_styles(name, created_at) values('Isbock', NOW());
insert into item_styles(name, created_at) values('Presentkartong 3 flaskor', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Pilsner - tjeckisk Stil', NOW());
insert into item_styles(name, created_at) values('Flaskförslutare Öl, cider & blanddrycker', NOW());
insert into item_styles(name, created_at) values('Vinförslutare', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Amber ale', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Brown ale', NOW());
insert into item_styles(name, created_at) values('Alkoholfri Dortmunder och helles', NOW());
insert into item_styles(name, created_at) values('Roséport', NOW());
