insert into item_types(name, created_at) values('Vodka', NOW());
insert into item_types(name, created_at) values('None', NOW());
insert into item_types(name, created_at) values('Ljus lager', NOW());
insert into item_types(name, created_at) values('Tequila', NOW());
insert into item_types(name, created_at) values('Mellanmörk lager', NOW());
insert into item_types(name, created_at) values('Mörk lager', NOW());
insert into item_types(name, created_at) values('Veteöl', NOW());
insert into item_types(name, created_at) values('Kryddat brännvin', NOW());
insert into item_types(name, created_at) values('Ale brittisk-amerikansk stil', NOW());
insert into item_types(name, created_at) values('Sherry & Montilla', NOW());
insert into item_types(name, created_at) values('Mörk rom', NOW());
insert into item_types(name, created_at) values('Portvin', NOW());
insert into item_types(name, created_at) values('Kryddlikör', NOW());
insert into item_types(name, created_at) values('Fruktigt & Smakrikt', NOW());
insert into item_types(name, created_at) values('Maltwhisky', NOW());
insert into item_types(name, created_at) values('Grainwhisky', NOW());
insert into item_types(name, created_at) values('Fylligt & Smakrikt', NOW());
insert into item_types(name, created_at) values('Friskt & Fruktigt', NOW());
insert into item_types(name, created_at) values('Gin', NOW());
insert into item_types(name, created_at) values('Torrt vitt', NOW());
insert into item_types(name, created_at) values('Kryddigt & Mustigt', NOW());
insert into item_types(name, created_at) values('Brandy', NOW());
insert into item_types(name, created_at) values('Söt', NOW());
insert into item_types(name, created_at) values('Smaksatt vodka', NOW());
insert into item_types(name, created_at) values('Stramt & Nyanserat', NOW());
insert into item_types(name, created_at) values('Porter och stout', NOW());
insert into item_types(name, created_at) values('Annan likör', NOW());
insert into item_types(name, created_at) values('Mjukt & Bärigt', NOW());
insert into item_types(name, created_at) values('Smaksatta viner & fruktviner', NOW());
insert into item_types(name, created_at) values('Akvavit', NOW());
insert into item_types(name, created_at) values('Syrlig öl', NOW());
insert into item_types(name, created_at) values('Öl', NOW());
insert into item_types(name, created_at) values('Rosé', NOW());
insert into item_types(name, created_at) values('Sött', NOW());
insert into item_types(name, created_at) values('Fruktlikör', NOW());
insert into item_types(name, created_at) values('Druvigt & Blommigt', NOW());
insert into item_types(name, created_at) values('Ale oklassificerat', NOW());
insert into item_types(name, created_at) values('Absint', NOW());
insert into item_types(name, created_at) values('1 flaska', NOW());
insert into item_types(name, created_at) values('2 flaskor', NOW());
insert into item_types(name, created_at) values('Bärlikör', NOW());
insert into item_types(name, created_at) values('Blended whisky', NOW());
insert into item_types(name, created_at) values('Mousserande', NOW());
insert into item_types(name, created_at) values('Aperitif', NOW());
insert into item_types(name, created_at) values('Mezcal', NOW());
insert into item_types(name, created_at) values('Ale belgisk stil', NOW());
insert into item_types(name, created_at) values('Fruktsprit', NOW());
insert into item_types(name, created_at) values('Ljus rom', NOW());
insert into item_types(name, created_at) values('Smaksatt', NOW());
insert into item_types(name, created_at) values('Genever', NOW());
insert into item_types(name, created_at) values('Torr och halvtorr', NOW());
insert into item_types(name, created_at) values('Gräddlikör', NOW());
insert into item_types(name, created_at) values('Vit söt', NOW());
insert into item_types(name, created_at) values('Vit torr', NOW());
insert into item_types(name, created_at) values('Örtlikör', NOW());
insert into item_types(name, created_at) values('Chokladlikör', NOW());
insert into item_types(name, created_at) values('Smaksatt sprit av rom', NOW());
insert into item_types(name, created_at) values('Armagnac', NOW());
insert into item_types(name, created_at) values('Halvtorrt vitt', NOW());
insert into item_types(name, created_at) values('Annan öl', NOW());
insert into item_types(name, created_at) values('Friskt & Bärigt', NOW());
insert into item_types(name, created_at) values('Punsch', NOW());
insert into item_types(name, created_at) values('Grappa', NOW());
insert into item_types(name, created_at) values('Smaksatt sprit', NOW());
insert into item_types(name, created_at) values('Övrigt starkvin', NOW());
insert into item_types(name, created_at) values('Ale tysk stil', NOW());
insert into item_types(name, created_at) values('Marc', NOW());
insert into item_types(name, created_at) values('Kaffelikör', NOW());
insert into item_types(name, created_at) values('Maltsprit', NOW());
insert into item_types(name, created_at) values('Bourbon', NOW());
insert into item_types(name, created_at) values('Vitt', NOW());
insert into item_types(name, created_at) values('Flergångskasse', NOW());
insert into item_types(name, created_at) values('Cider', NOW());
insert into item_types(name, created_at) values('6 flaskor', NOW());
insert into item_types(name, created_at) values('Annan whisky', NOW());
insert into item_types(name, created_at) values('Sött vitt', NOW());
insert into item_types(name, created_at) values('Övrigt', NOW());
insert into item_types(name, created_at) values('Glögg', NOW());
insert into item_types(name, created_at) values('Madeira', NOW());
insert into item_types(name, created_at) values('Arak', NOW());
insert into item_types(name, created_at) values('Förslutare', NOW());
insert into item_types(name, created_at) values('Ryewhisky', NOW());
insert into item_types(name, created_at) values('Pastis', NOW());
insert into item_types(name, created_at) values('Rött', NOW());
insert into item_types(name, created_at) values('Röd söt', NOW());
insert into item_types(name, created_at) values('Raki', NOW());
insert into item_types(name, created_at) values('Annan sprit av druvrester', NOW());
insert into item_types(name, created_at) values('Hällpip', NOW());
insert into item_types(name, created_at) values('Brännvin', NOW());
insert into item_types(name, created_at) values('Ouzo', NOW());
insert into item_types(name, created_at) values('Must', NOW());
insert into item_types(name, created_at) values('Nötlikör', NOW());
insert into item_types(name, created_at) values('Lätt & Avrundat', NOW());
insert into item_types(name, created_at) values('Vinkaraff', NOW());
insert into item_types(name, created_at) values('Aperitif och Bitter', NOW());
insert into item_types(name, created_at) values('Druvsprit', NOW());
insert into item_types(name, created_at) values('Korkskruv', NOW());
insert into item_types(name, created_at) values('Dekoration', NOW());
insert into item_types(name, created_at) values('Cornwhisky', NOW());
insert into item_types(name, created_at) values('Karafftillbehör', NOW());
insert into item_types(name, created_at) values('Arrak', NOW());
insert into item_types(name, created_at) values('Kylare', NOW());
insert into item_types(name, created_at) values('3 flaskor', NOW());
insert into item_types(name, created_at) values('Anissprit', NOW());
insert into item_types(name, created_at) values('Ägglikör', NOW());
insert into item_types(name, created_at) values('Vingas', NOW());
insert into item_types(name, created_at) values('Mätglas', NOW());
insert into item_types(name, created_at) values('Shaker', NOW());
