insert into item_types(name, created_at) values('Vodka', now());
insert into item_types(name, created_at) values('None', now());
insert into item_types(name, created_at) values('Ljus lager', now());
insert into item_types(name, created_at) values('Tequila', now());
insert into item_types(name, created_at) values('Mellanmörk lager', now());
insert into item_types(name, created_at) values('Mörk lager', now());
insert into item_types(name, created_at) values('Veteöl', now());
insert into item_types(name, created_at) values('Kryddat brännvin', now());
insert into item_types(name, created_at) values('Ale brittisk-amerikansk stil', now());
insert into item_types(name, created_at) values('Sherry & Montilla', now());
insert into item_types(name, created_at) values('Mörk rom', now());
insert into item_types(name, created_at) values('Portvin', now());
insert into item_types(name, created_at) values('Kryddlikör', now());
insert into item_types(name, created_at) values('Fruktigt & Smakrikt', now());
insert into item_types(name, created_at) values('Maltwhisky', now());
insert into item_types(name, created_at) values('Grainwhisky', now());
insert into item_types(name, created_at) values('Fylligt & Smakrikt', now());
insert into item_types(name, created_at) values('Friskt & Fruktigt', now());
insert into item_types(name, created_at) values('Gin', now());
insert into item_types(name, created_at) values('Torrt vitt', now());
insert into item_types(name, created_at) values('Kryddigt & Mustigt', now());
insert into item_types(name, created_at) values('Brandy', now());
insert into item_types(name, created_at) values('Söt', now());
insert into item_types(name, created_at) values('Smaksatt vodka', now());
insert into item_types(name, created_at) values('Stramt & Nyanserat', now());
insert into item_types(name, created_at) values('Porter och stout', now());
insert into item_types(name, created_at) values('Annan likör', now());
insert into item_types(name, created_at) values('Mjukt & Bärigt', now());
insert into item_types(name, created_at) values('Smaksatta viner & fruktviner', now());
insert into item_types(name, created_at) values('Akvavit', now());
insert into item_types(name, created_at) values('Syrlig öl', now());
insert into item_types(name, created_at) values('Öl', now());
insert into item_types(name, created_at) values('Rosé', now());
insert into item_types(name, created_at) values('Sött', now());
insert into item_types(name, created_at) values('Fruktlikör', now());
insert into item_types(name, created_at) values('Druvigt & Blommigt', now());
insert into item_types(name, created_at) values('Ale oklassificerat', now());
insert into item_types(name, created_at) values('Absint', now());
insert into item_types(name, created_at) values('1 flaska', now());
insert into item_types(name, created_at) values('2 flaskor', now());
insert into item_types(name, created_at) values('Bärlikör', now());
insert into item_types(name, created_at) values('Blended whisky', now());
insert into item_types(name, created_at) values('Mousserande', now());
insert into item_types(name, created_at) values('Aperitif', now());
insert into item_types(name, created_at) values('Mezcal', now());
insert into item_types(name, created_at) values('Ale belgisk stil', now());
insert into item_types(name, created_at) values('Fruktsprit', now());
insert into item_types(name, created_at) values('Ljus rom', now());
insert into item_types(name, created_at) values('Smaksatt', now());
insert into item_types(name, created_at) values('Genever', now());
insert into item_types(name, created_at) values('Torr och halvtorr', now());
insert into item_types(name, created_at) values('Gräddlikör', now());
insert into item_types(name, created_at) values('Vit söt', now());
insert into item_types(name, created_at) values('Vit torr', now());
insert into item_types(name, created_at) values('Örtlikör', now());
insert into item_types(name, created_at) values('Chokladlikör', now());
insert into item_types(name, created_at) values('Smaksatt sprit av rom', now());
insert into item_types(name, created_at) values('Armagnac', now());
insert into item_types(name, created_at) values('Halvtorrt vitt', now());
insert into item_types(name, created_at) values('Annan öl', now());
insert into item_types(name, created_at) values('Friskt & Bärigt', now());
insert into item_types(name, created_at) values('Punsch', now());
insert into item_types(name, created_at) values('Grappa', now());
insert into item_types(name, created_at) values('Smaksatt sprit', now());
insert into item_types(name, created_at) values('Övrigt starkvin', now());
insert into item_types(name, created_at) values('Ale tysk stil', now());
insert into item_types(name, created_at) values('Marc', now());
insert into item_types(name, created_at) values('Kaffelikör', now());
insert into item_types(name, created_at) values('Maltsprit', now());
insert into item_types(name, created_at) values('Bourbon', now());
insert into item_types(name, created_at) values('Vitt', now());
insert into item_types(name, created_at) values('Flergångskasse', now());
insert into item_types(name, created_at) values('Cider', now());
insert into item_types(name, created_at) values('6 flaskor', now());
insert into item_types(name, created_at) values('Annan whisky', now());
insert into item_types(name, created_at) values('Sött vitt', now());
insert into item_types(name, created_at) values('Övrigt', now());
insert into item_types(name, created_at) values('Glögg', now());
insert into item_types(name, created_at) values('Madeira', now());
insert into item_types(name, created_at) values('Arak', now());
insert into item_types(name, created_at) values('Förslutare', now());
insert into item_types(name, created_at) values('Ryewhisky', now());
insert into item_types(name, created_at) values('Pastis', now());
insert into item_types(name, created_at) values('Rött', now());
insert into item_types(name, created_at) values('Röd söt', now());
insert into item_types(name, created_at) values('Raki', now());
insert into item_types(name, created_at) values('Annan sprit av druvrester', now());
insert into item_types(name, created_at) values('Hällpip', now());
insert into item_types(name, created_at) values('Brännvin', now());
insert into item_types(name, created_at) values('Ouzo', now());
insert into item_types(name, created_at) values('Must', now());
insert into item_types(name, created_at) values('Nötlikör', now());
insert into item_types(name, created_at) values('Lätt & Avrundat', now());
insert into item_types(name, created_at) values('Vinkaraff', now());
insert into item_types(name, created_at) values('Aperitif och Bitter', now());
insert into item_types(name, created_at) values('Druvsprit', now());
insert into item_types(name, created_at) values('Korkskruv', now());
insert into item_types(name, created_at) values('Dekoration', now());
insert into item_types(name, created_at) values('Cornwhisky', now());
insert into item_types(name, created_at) values('Karafftillbehör', now());
insert into item_types(name, created_at) values('Arrak', now());
insert into item_types(name, created_at) values('Kylare', now());
insert into item_types(name, created_at) values('3 flaskor', now());
insert into item_types(name, created_at) values('Anissprit', now());
insert into item_types(name, created_at) values('Ägglikör', now());
insert into item_types(name, created_at) values('Vingas', now());
insert into item_types(name, created_at) values('Mätglas', now());
insert into item_types(name, created_at) values('Shaker', now());
