insert into item_styles(name, created_at) values('None', now());
insert into item_styles(name, created_at) values('Modern stil', now());
insert into item_styles(name, created_at) values('Märzen och wienerstil', now());
insert into item_styles(name, created_at) values('Dunkel', now());
insert into item_styles(name, created_at) values('Hefeweizen', now());
insert into item_styles(name, created_at) values('Pilsner - tysk stil', now());
insert into item_styles(name, created_at) values('Zwickel / keller- och landbier', now());
insert into item_styles(name, created_at) values('Dortmunder och helles', now());
insert into item_styles(name, created_at) values('India pale ale (IPA)', now());
insert into item_styles(name, created_at) values('Amerikansk pale ale (APA)', now());
insert into item_styles(name, created_at) values('Montilla', now());
insert into item_styles(name, created_at) values('Pilsner - tjeckisk stil', now());
insert into item_styles(name, created_at) values('Black IPA', now());
insert into item_styles(name, created_at) values('Tawny', now());
insert into item_styles(name, created_at) values('Amber ale', now());
insert into item_styles(name, created_at) values('Imperial porter och stout', now());
insert into item_styles(name, created_at) values('Imperial/Dubbel IPA', now());
insert into item_styles(name, created_at) values('Andra smaksatta viner & fruktviner', now());
insert into item_styles(name, created_at) values('Övrig syrlig öl', now());
insert into item_styles(name, created_at) values('Alkoholfri Amerikansk pale ale (APA)', now());
insert into item_styles(name, created_at) values('Vintage', now());
insert into item_styles(name, created_at) values('Flamländsk röd och brun öl', now());
insert into item_styles(name, created_at) values('Torr porter och stout', now());
insert into item_styles(name, created_at) values('Schwarzbier', now());
insert into item_styles(name, created_at) values('Presentkartong 1 flaska', now());
insert into item_styles(name, created_at) values('Presentkartong 2 flaskor', now());
insert into item_styles(name, created_at) values('Presentpåse 1 flaska', now());
insert into item_styles(name, created_at) values('Lambic - frukt och bär', now());
insert into item_styles(name, created_at) values('Amontillado', now());
insert into item_styles(name, created_at) values('Internationell stil', now());
insert into item_styles(name, created_at) values('Mjöd', now());
insert into item_styles(name, created_at) values('Sangria', now());
insert into item_styles(name, created_at) values('Engelsk pale ale och bitter', now());
insert into item_styles(name, created_at) values('Bière de garde', now());
insert into item_styles(name, created_at) values('Dubbelbock', now());
insert into item_styles(name, created_at) values('Late bottled vintage (LBV)', now());
insert into item_styles(name, created_at) values('Brown ale', now());
insert into item_styles(name, created_at) values('Saison', now());
insert into item_styles(name, created_at) values('Belgisk ljus ale', now());
insert into item_styles(name, created_at) values('Berliner weisse', now());
insert into item_styles(name, created_at) values('Session IPA', now());
insert into item_styles(name, created_at) values('Ljus bocköl', now());
insert into item_styles(name, created_at) values('Strong ale', now());
insert into item_styles(name, created_at) values('California common', now());
insert into item_styles(name, created_at) values('Öl av flera typer/stilar', now());
insert into item_styles(name, created_at) values('Belgisk mörk ale', now());
insert into item_styles(name, created_at) values('Alkoholfri Mörk lager', now());
insert into item_styles(name, created_at) values('Lambic - gueuze', now());
insert into item_styles(name, created_at) values('Barley wine', now());
insert into item_styles(name, created_at) values('Golden/Blond ale', now());
insert into item_styles(name, created_at) values('Witbier', now());
insert into item_styles(name, created_at) values('Ruby', now());
insert into item_styles(name, created_at) values('Kristallweizen', now());
insert into item_styles(name, created_at) values('Extra special bitter', now());
insert into item_styles(name, created_at) values('Trippel', now());
insert into item_styles(name, created_at) values('Annan sherry', now());
insert into item_styles(name, created_at) values('Presentkartong 6 flaskor', now());
insert into item_styles(name, created_at) values('Malmsey/malvasia', now());
insert into item_styles(name, created_at) values('Söt porter och stout', now());
insert into item_styles(name, created_at) values('Irländsk ale', now());
insert into item_styles(name, created_at) values('Sercial', now());
insert into item_styles(name, created_at) values('Manzanilla', now());
insert into item_styles(name, created_at) values('Cream sherry', now());
insert into item_styles(name, created_at) values('Dunkelweizen', now());
insert into item_styles(name, created_at) values('Starkare lager', now());
insert into item_styles(name, created_at) values('Alkoholfri Ljus lager', now());
insert into item_styles(name, created_at) values('Old ale', now());
insert into item_styles(name, created_at) values('Champagneförslutare', now());
insert into item_styles(name, created_at) values('Dubbel', now());
insert into item_styles(name, created_at) values('Colheita', now());
insert into item_styles(name, created_at) values('Altbier', now());
insert into item_styles(name, created_at) values('Mild', now());
insert into item_styles(name, created_at) values('Alkoholfri India pale ale', now());
insert into item_styles(name, created_at) values('Presentpåse 2 flaskor', now());
insert into item_styles(name, created_at) values('Alkoholfri Pilsner - tysk Stil', now());
insert into item_styles(name, created_at) values('Gose och lichtenhainer', now());
insert into item_styles(name, created_at) values('Alkoholfri Witbier', now());
insert into item_styles(name, created_at) values('Skotsk ale', now());
insert into item_styles(name, created_at) values('Alkoholfri Mellanmörk lager', now());
insert into item_styles(name, created_at) values('Imperial pils och india pale lager (IPL)', now());
insert into item_styles(name, created_at) values('Hopfenweizen', now());
insert into item_styles(name, created_at) values('Pedro ximénez (PX)', now());
insert into item_styles(name, created_at) values('Verdelho', now());
insert into item_styles(name, created_at) values('Alkoholfri Övrig syrlig öl', now());
insert into item_styles(name, created_at) values('Fino', now());
insert into item_styles(name, created_at) values('Abt och kvadrupel', now());
insert into item_styles(name, created_at) values('Polotmavý', now());
insert into item_styles(name, created_at) values('Alkoholfri Torr porter och stout', now());
insert into item_styles(name, created_at) values('Alkoholfri Engelsk pale ale och bitter', now());
insert into item_styles(name, created_at) values('Kölsch', now());
insert into item_styles(name, created_at) values('Annan madeira', now());
insert into item_styles(name, created_at) values('Vitt portvin', now());
insert into item_styles(name, created_at) values('Annat rött portvin', now());
insert into item_styles(name, created_at) values('Bual/boal', now());
insert into item_styles(name, created_at) values('Oloroso', now());
insert into item_styles(name, created_at) values('Alkoholfri Lambic - frukt och bär', now());
insert into item_styles(name, created_at) values('Alkoholfri Strong ale', now());
insert into item_styles(name, created_at) values('Förpackningsdekoration', now());
insert into item_styles(name, created_at) values('Weizenbock', now());
insert into item_styles(name, created_at) values('Alkoholfri Hefeweizen', now());
insert into item_styles(name, created_at) values('Champagnekylare', now());
insert into item_styles(name, created_at) values('Vinkylare', now());
insert into item_styles(name, created_at) values('Alkoholfri Zwickel, keller- och landbier', now());
insert into item_styles(name, created_at) values('Palo cortado', now());
insert into item_styles(name, created_at) values('Alkoholfri Internationell stil', now());
insert into item_styles(name, created_at) values('Isbock', now());
insert into item_styles(name, created_at) values('Presentkartong 3 flaskor', now());
insert into item_styles(name, created_at) values('Alkoholfri Pilsner - tjeckisk Stil', now());
insert into item_styles(name, created_at) values('Flaskförslutare Öl, cider & blanddrycker', now());
insert into item_styles(name, created_at) values('Vinförslutare', now());
insert into item_styles(name, created_at) values('Alkoholfri Amber ale', now());
insert into item_styles(name, created_at) values('Alkoholfri Brown ale', now());
insert into item_styles(name, created_at) values('Alkoholfri Dortmunder och helles', now());
insert into item_styles(name, created_at) values('Roséport', now());
