insert into suppliers(name, created_at) values('Pernod Ricard Sweden AB', NOW());
insert into suppliers(name, created_at) values('Vinoliv Import AB', NOW());
insert into suppliers(name, created_at) values('High Coast Wine AB', NOW());
insert into suppliers(name, created_at) values('Imperiebryggeriet  AB', NOW());
insert into suppliers(name, created_at) values('Fine Brands Sweden AB', NOW());
insert into suppliers(name, created_at) values('Dryckesboden Sverige AB', NOW());
insert into suppliers(name, created_at) values('CCS AB', NOW());
insert into suppliers(name, created_at) values('Sybaris - Wine & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Roslags Näsby Bryggeri', NOW());
insert into suppliers(name, created_at) values('Arcus Sweden AB', NOW());
insert into suppliers(name, created_at) values('Skelderwikens Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Halmstad Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Fjäderholmarnas Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('We & Wine AB', NOW());
insert into suppliers(name, created_at) values('Restaurang Skeppsgossen AB', NOW());
insert into suppliers(name, created_at) values('South Plains Brewing Company', NOW());
insert into suppliers(name, created_at) values('Granqvist Beverage House AB', NOW());
insert into suppliers(name, created_at) values('Vinobele AB', NOW());
insert into suppliers(name, created_at) values('Spendrups Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('AliasSmith AB', NOW());
insert into suppliers(name, created_at) values('Fields Wine Company AB', NOW());
insert into suppliers(name, created_at) values('Clydesdale AB', NOW());
insert into suppliers(name, created_at) values('Chris-Wine AB', NOW());
insert into suppliers(name, created_at) values('O.Wines and Spirits AB', NOW());
insert into suppliers(name, created_at) values('janake wine group AB', NOW());
insert into suppliers(name, created_at) values('Mackmyra Svensk Whisky AB', NOW());
insert into suppliers(name, created_at) values('Ward Wines AB', NOW());
insert into suppliers(name, created_at) values('The Wine Collection Sweden AB', NOW());
insert into suppliers(name, created_at) values('Johan Lidby Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Lancel AB', NOW());
insert into suppliers(name, created_at) values('Vinunic AB', NOW());
insert into suppliers(name, created_at) values('Giertz Vinimport AB', NOW());
insert into suppliers(name, created_at) values('The WineAgency Sweden AB', NOW());
insert into suppliers(name, created_at) values('Brands For Fans Sweden AB', NOW());
insert into suppliers(name, created_at) values('Hermansson & Co AB', NOW());
insert into suppliers(name, created_at) values('Skrubbes Wines AB', NOW());
insert into suppliers(name, created_at) values('Divine AB', NOW());
insert into suppliers(name, created_at) values('Enrico Sverige AB', NOW());
insert into suppliers(name, created_at) values('Tevsjö Destilleri i Järvsö AB', NOW());
insert into suppliers(name, created_at) values('Carovin AB', NOW());
insert into suppliers(name, created_at) values('Wine Lounge Stockholm AB', NOW());
insert into suppliers(name, created_at) values('Robert Rask Vinhandel', NOW());
insert into suppliers(name, created_at) values('Arvid Nordquist Vin och Sprithandel', NOW());
insert into suppliers(name, created_at) values('Great Brands AB', NOW());
insert into suppliers(name, created_at) values('TOMP Beer Wine & Spirits AB', NOW());
insert into suppliers(name, created_at) values('TM Kvalitetsviner AB', NOW());
insert into suppliers(name, created_at) values('Vivona AB', NOW());
insert into suppliers(name, created_at) values('Intermondi AB', NOW());
insert into suppliers(name, created_at) values('Altia Sweden AB', NOW());
insert into suppliers(name, created_at) values('Brewing Költur AB', NOW());
insert into suppliers(name, created_at) values('Oenoforos AB', NOW());
insert into suppliers(name, created_at) values('Rådanäs Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Svensk Cater AB', NOW());
insert into suppliers(name, created_at) values('Sigva AB', NOW());
insert into suppliers(name, created_at) values('Brewify AB', NOW());
insert into suppliers(name, created_at) values('Handpicked Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Winepartners Nordic AB', NOW());
insert into suppliers(name, created_at) values('Spivi AB', NOW());
insert into suppliers(name, created_at) values('Malchamax AB', NOW());
insert into suppliers(name, created_at) values('Cask Sweden AB', NOW());
insert into suppliers(name, created_at) values('Anno 1953 AB', NOW());
insert into suppliers(name, created_at) values('Mondo Wine Sweden AB', NOW());
insert into suppliers(name, created_at) values('Galatea AB', NOW());
insert into suppliers(name, created_at) values('Grythyttan Vin', NOW());
insert into suppliers(name, created_at) values('Åbro Bryggeri', NOW());
insert into suppliers(name, created_at) values('Asahi Sweden Filial', NOW());
insert into suppliers(name, created_at) values('Vinovativa AB', NOW());
insert into suppliers(name, created_at) values('Stellan Kramer AB', NOW());
insert into suppliers(name, created_at) values('ClosProbus KB', NOW());
insert into suppliers(name, created_at) values('Picky Drinks AB', NOW());
insert into suppliers(name, created_at) values('Dugges Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Nils Oscar AB', NOW());
insert into suppliers(name, created_at) values('WineWorld AB', NOW());
insert into suppliers(name, created_at) values('Carlsberg Sverige AB', NOW());
insert into suppliers(name, created_at) values('Vingården Bacina AB', NOW());
insert into suppliers(name, created_at) values('Samplex AB', NOW());
insert into suppliers(name, created_at) values('Triggollo Wine & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Quaffable Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Brandpartners AB', NOW());
insert into suppliers(name, created_at) values('Amka Vinimport AB', NOW());
insert into suppliers(name, created_at) values('Iconic Wines', NOW());
insert into suppliers(name, created_at) values('Moestue Grape Selections AB', NOW());
insert into suppliers(name, created_at) values('Brill & Co AB', NOW());
insert into suppliers(name, created_at) values('Lapland Water AB', NOW());
insert into suppliers(name, created_at) values('Domaine Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Brewery International Sweden AB', NOW());
insert into suppliers(name, created_at) values('Viña Española AB', NOW());
insert into suppliers(name, created_at) values('Bibendum', NOW());
insert into suppliers(name, created_at) values('Diageo Sweden AB', NOW());
insert into suppliers(name, created_at) values('Enjoy Wine & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Provinum Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Vinestor Sweden AB', NOW());
insert into suppliers(name, created_at) values('Jakobsson och Söderström AB', NOW());
insert into suppliers(name, created_at) values('Prime Wine Sweden AB', NOW());
insert into suppliers(name, created_at) values('Ametller Scandinavia - spanska produkter AB', NOW());
insert into suppliers(name, created_at) values('Terrific Wines AB', NOW());
insert into suppliers(name, created_at) values('Vega Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Contemporary wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Alingsås Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Åsalid Design', NOW());
insert into suppliers(name, created_at) values('Bornicon & Salming', NOW());
insert into suppliers(name, created_at) values('Valkyria Distillery AB', NOW());
insert into suppliers(name, created_at) values('Carlskrona Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Villa Aurum AB', NOW());
insert into suppliers(name, created_at) values('Premier Taste Sweden AB', NOW());
insert into suppliers(name, created_at) values('Vinia Sweden AB', NOW());
insert into suppliers(name, created_at) values('Jädraås Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Nacka Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Qvänum Mat & Malt AB', NOW());
insert into suppliers(name, created_at) values('Systembolaget Presenter', NOW());
insert into suppliers(name, created_at) values('Leufstabruk Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Pikulik, Peter', NOW());
insert into suppliers(name, created_at) values('Henkell Freixenet Sweden AB', NOW());
insert into suppliers(name, created_at) values('Bonne Box / Ett Ord AB', NOW());
insert into suppliers(name, created_at) values('Nelex Beverage AB', NOW());
insert into suppliers(name, created_at) values('Theis Vine AB', NOW());
insert into suppliers(name, created_at) values('Carlemår Wine & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Wine Affair Scandinavia AB', NOW());
insert into suppliers(name, created_at) values('Risotto Fine Foods & Wine', NOW());
insert into suppliers(name, created_at) values('Nigab', NOW());
insert into suppliers(name, created_at) values('Kämpinge Trading AB', NOW());
insert into suppliers(name, created_at) values('World Beer Trading KB', NOW());
insert into suppliers(name, created_at) values('AB Wicked Wine Sweden', NOW());
insert into suppliers(name, created_at) values('Runa Vodka AB', NOW());
insert into suppliers(name, created_at) values('Apricot AB', NOW());
insert into suppliers(name, created_at) values('Buteljholmen AB', NOW());
insert into suppliers(name, created_at) values('Tre Svampar AB', NOW());
insert into suppliers(name, created_at) values('Vinonista AB', NOW());
insert into suppliers(name, created_at) values('Nebbia HB', NOW());
insert into suppliers(name, created_at) values('Jämtlands Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Winemarket Nordic AB', NOW());
insert into suppliers(name, created_at) values('Grapestyle Scandinavia', NOW());
insert into suppliers(name, created_at) values('Vintedge AB', NOW());
insert into suppliers(name, created_at) values('RB Winery AB', NOW());
insert into suppliers(name, created_at) values('Mjödhamnen AB', NOW());
insert into suppliers(name, created_at) values('Dica Vin & Sprit HB', NOW());
insert into suppliers(name, created_at) values('Swedish Brand AB', NOW());
insert into suppliers(name, created_at) values('The Wine and Spirits Collective Sweden AB', NOW());
insert into suppliers(name, created_at) values('Vänersborgs Vinagentur AB', NOW());
insert into suppliers(name, created_at) values('Valid Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Herida Aurum AB', NOW());
insert into suppliers(name, created_at) values('Triplus Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Waxholms Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('GodDryck i Sverige AB', NOW());
insert into suppliers(name, created_at) values('Wine Group Sweden AB', NOW());
insert into suppliers(name, created_at) values('Winebee AB', NOW());
insert into suppliers(name, created_at) values('Corseimport', NOW());
insert into suppliers(name, created_at) values('Hjo Grosshandel AB', NOW());
insert into suppliers(name, created_at) values('Värmdö Bränneri AB', NOW());
insert into suppliers(name, created_at) values('Sundance Wines AB', NOW());
insert into suppliers(name, created_at) values('Krates Vin & Delikatesser', NOW());
insert into suppliers(name, created_at) values('Vino Conoscenza AB', NOW());
insert into suppliers(name, created_at) values('Cask Kompaniet AB', NOW());
insert into suppliers(name, created_at) values('People Wine AB', NOW());
insert into suppliers(name, created_at) values('Flying Brewery AB', NOW());
insert into suppliers(name, created_at) values('Greenery Wines KB', NOW());
insert into suppliers(name, created_at) values('Viness AB', NOW());
insert into suppliers(name, created_at) values('AB Svenska Sprit TBH', NOW());
insert into suppliers(name, created_at) values('Skellefteå Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('LarCap AB', NOW());
insert into suppliers(name, created_at) values('Remilio AB', NOW());
insert into suppliers(name, created_at) values('Hard On AB', NOW());
insert into suppliers(name, created_at) values('Edrington Sweden AB', NOW());
insert into suppliers(name, created_at) values('Gullberg by Stockwine AB', NOW());
insert into suppliers(name, created_at) values('AB Brygghuset Finn', NOW());
insert into suppliers(name, created_at) values('Remmarlöv Gårdsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Grebbestad Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Södra Maltfabriken AB', NOW());
insert into suppliers(name, created_at) values('Best Of Special Selected Wine AB', NOW());
insert into suppliers(name, created_at) values('Bristly Wine Agents AB', NOW());
insert into suppliers(name, created_at) values('Viniverdi Sweden AB', NOW());
insert into suppliers(name, created_at) values('Närke Kulturbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Kackelstugan AB', NOW());
insert into suppliers(name, created_at) values('Kiviks Musteri AB', NOW());
insert into suppliers(name, created_at) values('Barkonsult Jakobsson & Lövgren AB', NOW());
insert into suppliers(name, created_at) values('Treasury Wine Estates Sweden AB', NOW());
insert into suppliers(name, created_at) values('Fulltofta Gårdsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Doriani Wines AB', NOW());
insert into suppliers(name, created_at) values('Speedy Wine Store AB', NOW());
insert into suppliers(name, created_at) values('Rewine AB', NOW());
insert into suppliers(name, created_at) values('Smaken av Piemonte AB', NOW());
insert into suppliers(name, created_at) values('The Wine Team Global AB', NOW());
insert into suppliers(name, created_at) values('Brygghus 19 AB', NOW());
insert into suppliers(name, created_at) values('Sapordivino Sweden AB', NOW());
insert into suppliers(name, created_at) values('Sigva Partner AB', NOW());
insert into suppliers(name, created_at) values('Symposion AB', NOW());
insert into suppliers(name, created_at) values('ChampagneExperten by Västerås Sweden HB', NOW());
insert into suppliers(name, created_at) values('Happy Dog Dryckeshandel AB', NOW());
insert into suppliers(name, created_at) values('Juvinum Wine, Beer & Spirits AB', NOW());
insert into suppliers(name, created_at) values('VCT Sweden AB', NOW());
insert into suppliers(name, created_at) values('Moët Hennessy Sverige AB', NOW());
insert into suppliers(name, created_at) values('Nääs gårdsbryggeri', NOW());
insert into suppliers(name, created_at) values('Värmdö Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Walhöll Brygghus', NOW());
insert into suppliers(name, created_at) values('Sälens Fjällbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Råå Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Facile & Co AB', NOW());
insert into suppliers(name, created_at) values('Coppersmith AB', NOW());
insert into suppliers(name, created_at) values('Auld Rare Whisky Sweden AB', NOW());
insert into suppliers(name, created_at) values('Kasper Schönhult AB (Charlis Brygghus)', NOW());
insert into suppliers(name, created_at) values('Berntson Brands AB', NOW());
insert into suppliers(name, created_at) values('Sture Spirit AB', NOW());
insert into suppliers(name, created_at) values('Svenska Vinkompaniet', NOW());
insert into suppliers(name, created_at) values('Smaksinnet AB', NOW());
insert into suppliers(name, created_at) values('Zebrawine i Uppsala AB', NOW());
insert into suppliers(name, created_at) values('Principium Dryck AB', NOW());
insert into suppliers(name, created_at) values('Avivera AB', NOW());
insert into suppliers(name, created_at) values('ExpertWine Naturvin AB', NOW());
insert into suppliers(name, created_at) values('Kopparbergs Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Vintrio Wine AB', NOW());
insert into suppliers(name, created_at) values('Les Millésimes HB', NOW());
insert into suppliers(name, created_at) values('Conveija Aktiebolag', NOW());
insert into suppliers(name, created_at) values('Alshammar Import', NOW());
insert into suppliers(name, created_at) values('Verissima AB', NOW());
insert into suppliers(name, created_at) values('Brix Wine Consultants AB', NOW());
insert into suppliers(name, created_at) values('Skepparps Vingård', NOW());
insert into suppliers(name, created_at) values('Lively Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Vinovum AB', NOW());
insert into suppliers(name, created_at) values('Fine Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Dalelven Holding AB', NOW());
insert into suppliers(name, created_at) values('Ofwerman Imports AB', NOW());
insert into suppliers(name, created_at) values('2Goda Vin & Bryggeri', NOW());
insert into suppliers(name, created_at) values('Nippon Sake Sweden AB', NOW());
insert into suppliers(name, created_at) values('Fisherstorm Filial til Berentsens Brygghus AS Norway', NOW());
insert into suppliers(name, created_at) values('Ahlafors Bryggerier AB', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Centralbryggeriet i Linköping', NOW());
insert into suppliers(name, created_at) values('Sibbarps Husbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Concealed Wines AB', NOW());
insert into suppliers(name, created_at) values('Independent Wine Company AB', NOW());
insert into suppliers(name, created_at) values('Bryggeriaktiebolaget Nya Victoria', NOW());
insert into suppliers(name, created_at) values('Origo Wine Import', NOW());
insert into suppliers(name, created_at) values('Pite Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('VinTillMat i Väst AB', NOW());
insert into suppliers(name, created_at) values('The Beer Factory Leksand AB', NOW());
insert into suppliers(name, created_at) values('Roslagens Brygghus AB', NOW());
insert into suppliers(name, created_at) values('UP Wine', NOW());
insert into suppliers(name, created_at) values('Mission Wine & Spirit AB', NOW());
insert into suppliers(name, created_at) values('Wermlands Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Beer Me Sweden AB', NOW());
insert into suppliers(name, created_at) values('Jackdaw Brewery AB', NOW());
insert into suppliers(name, created_at) values('Poppels Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Nordmarkens Destilleri AB', NOW());
insert into suppliers(name, created_at) values('Snickerivägens bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Wembrands World AB', NOW());
insert into suppliers(name, created_at) values('Ludvig Sääf', NOW());
insert into suppliers(name, created_at) values('VinoNovo AB', NOW());
insert into suppliers(name, created_at) values('Gamla Slottskällans Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('AB Hantverksöl Gamla Enskede', NOW());
insert into suppliers(name, created_at) values('Renbjer & Magnusson AB', NOW());
insert into suppliers(name, created_at) values('Vendemmia Vinimport AB', NOW());
insert into suppliers(name, created_at) values('Ocean Brewery AB', NOW());
insert into suppliers(name, created_at) values('Multibev AB', NOW());
insert into suppliers(name, created_at) values('Sofrakis Murat', NOW());
insert into suppliers(name, created_at) values('Klackabackens bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Kaffak AB', NOW());
insert into suppliers(name, created_at) values('Wannborga på Öland AB', NOW());
insert into suppliers(name, created_at) values('Bålsta Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Ysäter AB', NOW());
insert into suppliers(name, created_at) values('Tuesday Wine AB', NOW());
insert into suppliers(name, created_at) values('Michael Malmbom', NOW());
insert into suppliers(name, created_at) values('Uppsala Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Sahlins Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Viken Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Wapnö AB', NOW());
insert into suppliers(name, created_at) values('Brewtrade Sweden AB', NOW());
insert into suppliers(name, created_at) values('Sundbybergs köksbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Västra Ämterviks Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Härjedalens bryggeriaktiebolag', NOW());
insert into suppliers(name, created_at) values('Carlstad bryggeri KB', NOW());
insert into suppliers(name, created_at) values('Modernist Brewery AB', NOW());
insert into suppliers(name, created_at) values('Selected French Wine Nordic HB', NOW());
insert into suppliers(name, created_at) values('Old Cowhouse Brewery AB', NOW());
insert into suppliers(name, created_at) values('Götene Vin & Spritfabrik AB', NOW());
insert into suppliers(name, created_at) values('Whiskytaste Sweden AB', NOW());
insert into suppliers(name, created_at) values('Bacardi AB', NOW());
insert into suppliers(name, created_at) values('Rhuby AB', NOW());
insert into suppliers(name, created_at) values('Nice Wine i Jönköping AB', NOW());
insert into suppliers(name, created_at) values('Fiskebäcksbryggeriet AB', NOW());
insert into suppliers(name, created_at) values('Netterberg & Co AB', NOW());
insert into suppliers(name, created_at) values('Den Bryggande Holländaren AB', NOW());
insert into suppliers(name, created_at) values('Limhamns Bryggeri', NOW());
insert into suppliers(name, created_at) values('Örebro Brygghus i Nerike AB', NOW());
insert into suppliers(name, created_at) values('Skånska Spritfabriken', NOW());
insert into suppliers(name, created_at) values('Euroway Airline', NOW());
insert into suppliers(name, created_at) values('Fors Bryggeri KB', NOW());
insert into suppliers(name, created_at) values('Selbac AB', NOW());
insert into suppliers(name, created_at) values('Meadow Valley Wines', NOW());
insert into suppliers(name, created_at) values('Orbaden Zip & Climb AB', NOW());
insert into suppliers(name, created_at) values('Albert&Lily AB', NOW());
insert into suppliers(name, created_at) values('Vini Buoni AB', NOW());
insert into suppliers(name, created_at) values('U and Me Beer AB', NOW());
insert into suppliers(name, created_at) values('Bryggverket AB', NOW());
insert into suppliers(name, created_at) values('Beer Studio AB', NOW());
insert into suppliers(name, created_at) values('Emmaboda Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Ferna Forge Brewery AB', NOW());
insert into suppliers(name, created_at) values('Nora Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Bergslagens Destilleri Örebro AB', NOW());
insert into suppliers(name, created_at) values('Alskute Farm & Brewery AB', NOW());
insert into suppliers(name, created_at) values('Joyride Wine', NOW());
insert into suppliers(name, created_at) values('Hemberga Dryckesgrossisten AB', NOW());
insert into suppliers(name, created_at) values('Göteborgs Vinhandelshus AB', NOW());
insert into suppliers(name, created_at) values('JPC Wines AB', NOW());
insert into suppliers(name, created_at) values('Båstad Wine & Champagne AB', NOW());
insert into suppliers(name, created_at) values('Liquorama AB', NOW());
insert into suppliers(name, created_at) values('Helsingborgs Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('GPS Good Public Spirit AB', NOW());
insert into suppliers(name, created_at) values('Saturnus', NOW());
insert into suppliers(name, created_at) values('Norrtelje Brenneri AB', NOW());
insert into suppliers(name, created_at) values('Winehouse Bilberg', NOW());
insert into suppliers(name, created_at) values('Cantina del Re HB', NOW());
insert into suppliers(name, created_at) values('E&E Wine / Pamela Lundin', NOW());
insert into suppliers(name, created_at) values('Hults Dryck & Delikatess AB', NOW());
insert into suppliers(name, created_at) values('Elixir HB', NOW());
insert into suppliers(name, created_at) values('Vinopia Wine & Spirit AB', NOW());
insert into suppliers(name, created_at) values('VinBistro Stockholm AB', NOW());
insert into suppliers(name, created_at) values('Zemela Wines AB', NOW());
insert into suppliers(name, created_at) values('Omnipollo AB', NOW());
insert into suppliers(name, created_at) values('Möllys AB', NOW());
insert into suppliers(name, created_at) values('MakarnaSvärd', NOW());
insert into suppliers(name, created_at) values('Göteborgs Nya Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Alnöl AB', NOW());
insert into suppliers(name, created_at) values('Höganäs Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Pax Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Lobia AB', NOW());
insert into suppliers(name, created_at) values('Scandinavian Wine & Food KB', NOW());
insert into suppliers(name, created_at) values('Solo io', NOW());
insert into suppliers(name, created_at) values('Nordic Kiwi Brewers AB', NOW());
insert into suppliers(name, created_at) values('GL Brands AB', NOW());
insert into suppliers(name, created_at) values('Wine Brothers & Co', NOW());
insert into suppliers(name, created_at) values('Tirage AB', NOW());
insert into suppliers(name, created_at) values('MarBec AB', NOW());
insert into suppliers(name, created_at) values('Sibbetorps Gård AB', NOW());
insert into suppliers(name, created_at) values('Hönsinge Hantwerksbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Södermännens Hantverksbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Calwine AB', NOW());
insert into suppliers(name, created_at) values('Tegnér Spirits & Wine AB', NOW());
insert into suppliers(name, created_at) values('Sandahl International AB', NOW());
insert into suppliers(name, created_at) values('Swedish Wine Cellar AB', NOW());
insert into suppliers(name, created_at) values('Boucarou Wine & Dine AB', NOW());
insert into suppliers(name, created_at) values('Lowther & Partners AB', NOW());
insert into suppliers(name, created_at) values('Mora Bryggeri', NOW());
insert into suppliers(name, created_at) values('Kullabygdens Destilleri AB', NOW());
insert into suppliers(name, created_at) values('Olof af Wåhlberg', NOW());
insert into suppliers(name, created_at) values('AB InBev Sweden', NOW());
insert into suppliers(name, created_at) values('Vinolio AB', NOW());
insert into suppliers(name, created_at) values('Original Brands STHLM HB', NOW());
insert into suppliers(name, created_at) values('Sophronie AB', NOW());
insert into suppliers(name, created_at) values('Box Destilleri AB / High Coast', NOW());
insert into suppliers(name, created_at) values('Beerbliotek AB', NOW());
insert into suppliers(name, created_at) values('Torsöl Mikrobryggeri', NOW());
insert into suppliers(name, created_at) values('1413 Bryggkultur AB', NOW());
insert into suppliers(name, created_at) values('BarlindBeer AB', NOW());
insert into suppliers(name, created_at) values('Bearded Rabbit Brewery AB', NOW());
insert into suppliers(name, created_at) values('Bröderna Bommen AB', NOW());
insert into suppliers(name, created_at) values('Men Of Spirit AB', NOW());
insert into suppliers(name, created_at) values('House of Liquids', NOW());
insert into suppliers(name, created_at) values('Isles of Wines AB', NOW());
insert into suppliers(name, created_at) values('Sydamerikaviner AB', NOW());
insert into suppliers(name, created_at) values('Cavarosa Wine AB', NOW());
insert into suppliers(name, created_at) values('Prins Katts Hantverksöl', NOW());
insert into suppliers(name, created_at) values('MN Choklad AB', NOW());
insert into suppliers(name, created_at) values('Sysskonhem Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Skogh Development Design AB', NOW());
insert into suppliers(name, created_at) values('Mjelga Hantverksbryggeri', NOW());
insert into suppliers(name, created_at) values('Stockholms Bränneri AB', NOW());
insert into suppliers(name, created_at) values('Östgötaslättens produktion AB', NOW());
insert into suppliers(name, created_at) values('Foodspice', NOW());
insert into suppliers(name, created_at) values('Yolana Mode', NOW());
insert into suppliers(name, created_at) values('Barlingbo Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Gamla Hesselby Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Strandlida Hopspace AB', NOW());
insert into suppliers(name, created_at) values('LOMO International AB', NOW());
insert into suppliers(name, created_at) values('Runemount Scandinavia AB', NOW());
insert into suppliers(name, created_at) values('Argoria AB', NOW());
insert into suppliers(name, created_at) values('Champagnekällaren i Sverige AB', NOW());
insert into suppliers(name, created_at) values('Hernö Hantverksöl AB', NOW());
insert into suppliers(name, created_at) values('Margareta Laike', NOW());
insert into suppliers(name, created_at) values('Pine Bridge Brewery AB', NOW());
insert into suppliers(name, created_at) values('Revsunds Brewery AB', NOW());
insert into suppliers(name, created_at) values('Spike Brewery AB', NOW());
insert into suppliers(name, created_at) values('O.I.B AB', NOW());
insert into suppliers(name, created_at) values('Train Station Brewery AB', NOW());
insert into suppliers(name, created_at) values('Preuss International AB', NOW());
insert into suppliers(name, created_at) values('Svensk Absint AB', NOW());
insert into suppliers(name, created_at) values('Wessingekälla Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Åhus 57:5 AB', NOW());
insert into suppliers(name, created_at) values('Ängöl AB', NOW());
insert into suppliers(name, created_at) values('Grand Labels AB', NOW());
insert into suppliers(name, created_at) values('Spirits of Passion AB', NOW());
insert into suppliers(name, created_at) values('Ahlén & Small Trading AB', NOW());
insert into suppliers(name, created_at) values('Mouette Swedish Wine Import', NOW());
insert into suppliers(name, created_at) values('Burgsviks Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Thompson Consulting & Trading', NOW());
insert into suppliers(name, created_at) values('Herdenstam Vinhandel', NOW());
insert into suppliers(name, created_at) values('House of Wine Georgia AB', NOW());
insert into suppliers(name, created_at) values('Wine Rebels HB', NOW());
insert into suppliers(name, created_at) values('Euskadi Wine & Spirits', NOW());
insert into suppliers(name, created_at) values('tottOvin', NOW());
insert into suppliers(name, created_at) values('Riktig Cider', NOW());
insert into suppliers(name, created_at) values('The Company of Urban wines&Other Liquids Sweden', NOW());
insert into suppliers(name, created_at) values('Taste of Mallorca AB', NOW());
insert into suppliers(name, created_at) values('Oppigårds Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Åkersberga Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Spruce Up AB', NOW());
insert into suppliers(name, created_at) values('Dykes Brewery AB', NOW());
insert into suppliers(name, created_at) values('Grästorps Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Teknikservice i Torrskog', NOW());
insert into suppliers(name, created_at) values('Hönöbryggeriet AB', NOW());
insert into suppliers(name, created_at) values('Bergslagens Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Wine Trade Sweden AB', NOW());
insert into suppliers(name, created_at) values('Ybenets Wine AB', NOW());
insert into suppliers(name, created_at) values('Hops N" Leon of Skaraborg AB', NOW());
insert into suppliers(name, created_at) values('Vin & Natur Malmö AB', NOW());
insert into suppliers(name, created_at) values('Uppsala Destilleri AB', NOW());
insert into suppliers(name, created_at) values('Kvarnagårdens Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Idlewild AB', NOW());
insert into suppliers(name, created_at) values('The Uncharted Brewing Company AB', NOW());
insert into suppliers(name, created_at) values('Sangiro AB', NOW());
insert into suppliers(name, created_at) values('Figeholms Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('ÅBC Åredalens BryggCompagni AB', NOW());
insert into suppliers(name, created_at) values('Kullens Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Wine Selection, Amongré AB', NOW());
insert into suppliers(name, created_at) values('Gårdsbryggeriet 65°N', NOW());
insert into suppliers(name, created_at) values('Hop Shed Brewery AB', NOW());
insert into suppliers(name, created_at) values('Dryckesbutiken Timotejgatan AB', NOW());
insert into suppliers(name, created_at) values('Vattudalen Whisky Handelsbolag', NOW());
insert into suppliers(name, created_at) values('Tappers Bryggeri & Musteri AB', NOW());
insert into suppliers(name, created_at) values('Good Guys Brew AB', NOW());
insert into suppliers(name, created_at) values('Kornheddinge BryggeriKompani AB', NOW());
insert into suppliers(name, created_at) values('Josefin Lagerhorn', NOW());
insert into suppliers(name, created_at) values('Lockeby Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Hantverksbryggeriet AB', NOW());
insert into suppliers(name, created_at) values('Flädie Vinproduktion AB', NOW());
insert into suppliers(name, created_at) values('Tjers Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Gotland Whisky AB', NOW());
insert into suppliers(name, created_at) values('Norrlandsbryggarna AB', NOW());
insert into suppliers(name, created_at) values('Core Wine AB', NOW());
insert into suppliers(name, created_at) values('Hvellinge Spritfabriks AB', NOW());
insert into suppliers(name, created_at) values('Dryck STHLM Retail AB', NOW());
insert into suppliers(name, created_at) values('Wine Detectives AB', NOW());
insert into suppliers(name, created_at) values('Portofoliowines AB', NOW());
insert into suppliers(name, created_at) values('Hübsch Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Andalucia Wines', NOW());
insert into suppliers(name, created_at) values('Starkstrom Wineimport Limited UK', NOW());
insert into suppliers(name, created_at) values('Barrels and Kegs AB', NOW());
insert into suppliers(name, created_at) values('Engsdalens Vin AB', NOW());
insert into suppliers(name, created_at) values('Södra Stockholms Brygghus', NOW());
insert into suppliers(name, created_at) values('Vin Champagne Produits de France AB', NOW());
insert into suppliers(name, created_at) values('Freixenet Nordic AB', NOW());
insert into suppliers(name, created_at) values('Bra sprit i Sverige AB', NOW());
insert into suppliers(name, created_at) values('W&B of Sweden AB', NOW());
insert into suppliers(name, created_at) values('Havas & Co', NOW());
insert into suppliers(name, created_at) values('137:ans Beer & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Bottenvikens bryggeri', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Nyckelbryggerier', NOW());
insert into suppliers(name, created_at) values('Billdale & Co AB', NOW());
insert into suppliers(name, created_at) values('Ryssby bryggeri', NOW());
insert into suppliers(name, created_at) values('Gammelbacka Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Håks Gård', NOW());
insert into suppliers(name, created_at) values('Inlands Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Möllys', NOW());
insert into suppliers(name, created_at) values('GustaVino AB', NOW());
insert into suppliers(name, created_at) values('Jemtehed & Brande AB', NOW());
insert into suppliers(name, created_at) values('Reinklou Bryggerier AB', NOW());
insert into suppliers(name, created_at) values('Beersmiths AB', NOW());
insert into suppliers(name, created_at) values('Marbäcks Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Kronhuset Trading AB', NOW());
insert into suppliers(name, created_at) values('Nynäshamns Ångbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Umida Partners AB', NOW());
insert into suppliers(name, created_at) values('Papilles food & beverage AB', NOW());
insert into suppliers(name, created_at) values('VelvetBox AB', NOW());
insert into suppliers(name, created_at) values('Arcus WineBrands Sweden AB', NOW());
insert into suppliers(name, created_at) values('Bandol Import HB', NOW());
insert into suppliers(name, created_at) values('DiMalda AB', NOW());
insert into suppliers(name, created_at) values('APC China Trading AB', NOW());
insert into suppliers(name, created_at) values('VD Wines AB', NOW());
insert into suppliers(name, created_at) values('Din Mässpartner i Örebro', NOW());
insert into suppliers(name, created_at) values('Stallhagen AB Sverige Filial', NOW());
insert into suppliers(name, created_at) values('Wet Whistle Brewery AB', NOW());
insert into suppliers(name, created_at) values('Tempel Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Lost Island Brewery AB', NOW());
insert into suppliers(name, created_at) values('Bryggeri Rosenhill AB', NOW());
insert into suppliers(name, created_at) values('Eskilstuna Ölkultur AB', NOW());
insert into suppliers(name, created_at) values('ProConWine AB', NOW());
insert into suppliers(name, created_at) values('Providential Wines & Spirits AB', NOW());
insert into suppliers(name, created_at) values('Carl Vin & Wine AB', NOW());
insert into suppliers(name, created_at) values('Träkumla Rom AB', NOW());
insert into suppliers(name, created_at) values('Johan Matsanders', NOW());
insert into suppliers(name, created_at) values('Mälardalens Frukt & Grönt i Västerås AB', NOW());
insert into suppliers(name, created_at) values('Wineshare Sweden Stig Calderon', NOW());
insert into suppliers(name, created_at) values('Noham Group AB', NOW());
insert into suppliers(name, created_at) values('AvecSweden AB', NOW());
insert into suppliers(name, created_at) values('Backafallsbyn AB', NOW());
insert into suppliers(name, created_at) values('Norbotnia Whisky HB', NOW());
insert into suppliers(name, created_at) values('Gastrodev Vin & Sprit AB', NOW());
insert into suppliers(name, created_at) values('Scala Wines Import AB', NOW());
insert into suppliers(name, created_at) values('GefleBockens Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Högberga Vinfabrik AB', NOW());
insert into suppliers(name, created_at) values('Björketorp Consulting AB', NOW());
insert into suppliers(name, created_at) values('UPP Brewing AB', NOW());
insert into suppliers(name, created_at) values('BSSK IMPEX AB', NOW());
insert into suppliers(name, created_at) values('Länna Bruk Dryckeshandel AB', NOW());
insert into suppliers(name, created_at) values('Selbo Consulting AB', NOW());
insert into suppliers(name, created_at) values('Bakalar AB', NOW());
insert into suppliers(name, created_at) values('Arvika bryggeri', NOW());
insert into suppliers(name, created_at) values('Stjernsund Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Ottsjö Café AB', NOW());
insert into suppliers(name, created_at) values('Trosa Ölkompani AB', NOW());
insert into suppliers(name, created_at) values('Wine Mechanics AB', NOW());
insert into suppliers(name, created_at) values('Vareböke Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Sydamerikaviner HB', NOW());
insert into suppliers(name, created_at) values('SWSwine Köksinredarna Björkman Design AB', NOW());
insert into suppliers(name, created_at) values('Vinetum AB', NOW());
insert into suppliers(name, created_at) values('Enoterra AB', NOW());
insert into suppliers(name, created_at) values('Tjaerdalen Beer & Whisky AB', NOW());
insert into suppliers(name, created_at) values('Dryckesbolaget Gustav Vasa AB', NOW());
insert into suppliers(name, created_at) values('Bevalta AB', NOW());
insert into suppliers(name, created_at) values('P A Nilsson Vinhandel', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Old Road and Friends', NOW());
insert into suppliers(name, created_at) values('Två Feta Grisar AB', NOW());
insert into suppliers(name, created_at) values('Extra Mile HB', NOW());
insert into suppliers(name, created_at) values('Svartbergets Café & Restaurang AB', NOW());
insert into suppliers(name, created_at) values('Sad Robot Brewing AB', NOW());
insert into suppliers(name, created_at) values('Brewgineers AB', NOW());
insert into suppliers(name, created_at) values('Villovägens Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Stigbergets bryggeri AB', NOW());
insert into suppliers(name, created_at) values('AB Mohawk Brewing Company', NOW());
insert into suppliers(name, created_at) values('Mjödner AB', NOW());
insert into suppliers(name, created_at) values('Svenska Eldvatten AB', NOW());
insert into suppliers(name, created_at) values('Kollektivet Dryckeshandel AB', NOW());
insert into suppliers(name, created_at) values('Quid Vis Vin AB', NOW());
insert into suppliers(name, created_at) values('Krönleins', NOW());
insert into suppliers(name, created_at) values('M"s Winery AB', NOW());
insert into suppliers(name, created_at) values('Heba Food & Beverages AB', NOW());
insert into suppliers(name, created_at) values('Gusto Divino i Göteborg AB', NOW());
insert into suppliers(name, created_at) values('Top Note Wine AB', NOW());
insert into suppliers(name, created_at) values('Sebastian Jofre Armijo', NOW());
insert into suppliers(name, created_at) values('Uddevalla Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Agathos AB', NOW());
insert into suppliers(name, created_at) values('Rocket Brewing Company AB', NOW());
insert into suppliers(name, created_at) values('Arilds vingård AB', NOW());
insert into suppliers(name, created_at) values('Idunn Norsjö Wine & Co AB', NOW());
insert into suppliers(name, created_at) values('Fireside Inn AB', NOW());
insert into suppliers(name, created_at) values('Kyrkeby Bränneri AB', NOW());
insert into suppliers(name, created_at) values('Subbe Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Westerbottens Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Byaregårdens Brygghus HB', NOW());
insert into suppliers(name, created_at) values('Constant Companion AB', NOW());
insert into suppliers(name, created_at) values('Dervana AB', NOW());
insert into suppliers(name, created_at) values('Trollsås & Partners AB', NOW());
insert into suppliers(name, created_at) values('1423 Noble Spirit AB', NOW());
insert into suppliers(name, created_at) values('New Frontier Wines AB', NOW());
insert into suppliers(name, created_at) values('Pompette AB', NOW());
insert into suppliers(name, created_at) values('Långviks Krydderi & Handel', NOW());
insert into suppliers(name, created_at) values('Caves du Vineum i Sverige AB', NOW());
insert into suppliers(name, created_at) values('Ödåkra Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Bedstekilde - Vin av äpplen AB', NOW());
insert into suppliers(name, created_at) values('Wine Stain AB', NOW());
insert into suppliers(name, created_at) values('Liyu Handel', NOW());
insert into suppliers(name, created_at) values('Brasstacks Brewing Company AB', NOW());
insert into suppliers(name, created_at) values('Almby Brewery', NOW());
insert into suppliers(name, created_at) values('Mälardalen Brewing Company', NOW());
insert into suppliers(name, created_at) values('Stockholms Vinhus AB', NOW());
insert into suppliers(name, created_at) values('Gardo & Morris AB', NOW());
insert into suppliers(name, created_at) values('Sakeman & Sakesson AB', NOW());
insert into suppliers(name, created_at) values('Akebono Unlimited AB', NOW());
insert into suppliers(name, created_at) values('Deliq AB', NOW());
insert into suppliers(name, created_at) values('Nordic Liquids AB', NOW());
insert into suppliers(name, created_at) values('Canwine HB', NOW());
insert into suppliers(name, created_at) values('Green Premium Wine Gardeproduction', NOW());
insert into suppliers(name, created_at) values('En halvpall AB', NOW());
insert into suppliers(name, created_at) values('Stålhammars drycker AB', NOW());
insert into suppliers(name, created_at) values('UniTrends AB', NOW());
insert into suppliers(name, created_at) values('Pilsnergubbarna i Ulricehamn AB', NOW());
insert into suppliers(name, created_at) values('Rudolf Pétillant AB', NOW());
insert into suppliers(name, created_at) values('Femtorp AB', NOW());
insert into suppliers(name, created_at) values('Conaxess Trade Sweden AB', NOW());
insert into suppliers(name, created_at) values('ChampagneHuset CH', NOW());
insert into suppliers(name, created_at) values('Beskows Drycker AB', NOW());
insert into suppliers(name, created_at) values('Grönsöö Säteri AB', NOW());
insert into suppliers(name, created_at) values('Maglehems Musteri AB', NOW());
insert into suppliers(name, created_at) values('Axel Oliver Wine', NOW());
insert into suppliers(name, created_at) values('Savino AB', NOW());
insert into suppliers(name, created_at) values('Obrini Beverage Company AB', NOW());
insert into suppliers(name, created_at) values('Pardon My French AB', NOW());
insert into suppliers(name, created_at) values('Frutoso International AB', NOW());
insert into suppliers(name, created_at) values('Staffan Ottosson', NOW());
insert into suppliers(name, created_at) values('Spishyllan AB', NOW());
insert into suppliers(name, created_at) values('Kiruna Bryggeri Aktiebolag', NOW());
insert into suppliers(name, created_at) values('Sthlm Brewing Co AB', NOW());
insert into suppliers(name, created_at) values('P Skoogs Vinhandel i Öresund AB', NOW());
insert into suppliers(name, created_at) values('Loopen Marin AB', NOW());
insert into suppliers(name, created_at) values('Råda Bubbel AB', NOW());
insert into suppliers(name, created_at) values('Stripabryggeriet AB', NOW());
insert into suppliers(name, created_at) values('Gardshol Wines AB', NOW());
insert into suppliers(name, created_at) values('Smaland Brewing AB', NOW());
insert into suppliers(name, created_at) values('Sommestad & Malmnäs AB', NOW());
insert into suppliers(name, created_at) values('Standout Brands AB', NOW());
insert into suppliers(name, created_at) values('Perpetuelle AB', NOW());
insert into suppliers(name, created_at) values('Chastel Beverage KB', NOW());
insert into suppliers(name, created_at) values('Golden Alco', NOW());
insert into suppliers(name, created_at) values('Belgodeli', NOW());
insert into suppliers(name, created_at) values('KallsaUtbildningsConsult', NOW());
insert into suppliers(name, created_at) values('Otto Suenson & Co AB', NOW());
insert into suppliers(name, created_at) values('Beerium Kraftölsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Meadgard AB', NOW());
insert into suppliers(name, created_at) values('Lundabryggeriet AB', NOW());
insert into suppliers(name, created_at) values('Strömsholms Brygghus', NOW());
insert into suppliers(name, created_at) values('European Wine & Beverage', NOW());
insert into suppliers(name, created_at) values('Fontana Food AB', NOW());
insert into suppliers(name, created_at) values('Bryggeri 1766', NOW());
insert into suppliers(name, created_at) values('Alafors Kvarnen i Anneberg Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Kullabergs Vingård AB', NOW());
insert into suppliers(name, created_at) values('Veritabel Vin AB', NOW());
insert into suppliers(name, created_at) values('Keane Brewing AB', NOW());
insert into suppliers(name, created_at) values('Fermenterarna Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('O/O Brewing AB', NOW());
insert into suppliers(name, created_at) values('Stockholm Wine Importers AB', NOW());
insert into suppliers(name, created_at) values('Scientific Lab Glass AB', NOW());
insert into suppliers(name, created_at) values('Bondi AB', NOW());
insert into suppliers(name, created_at) values('LXR Wines HB', NOW());
insert into suppliers(name, created_at) values('Norrlöf Nils Åke Patrik', NOW());
insert into suppliers(name, created_at) values('Södåkra Vingård HB', NOW());
insert into suppliers(name, created_at) values('Kustens Gårdsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Allsta Bryggeri', NOW());
insert into suppliers(name, created_at) values('Havsjö Delikatesser AB', NOW());
insert into suppliers(name, created_at) values('Lilla Ölfabriken PP AB', NOW());
insert into suppliers(name, created_at) values('Bustad Brewing AB', NOW());
insert into suppliers(name, created_at) values('Triplicity Brewing AB', NOW());
insert into suppliers(name, created_at) values('Gute Vingård AB', NOW());
insert into suppliers(name, created_at) values('Säbyholms Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Fermenteriet AB', NOW());
insert into suppliers(name, created_at) values('Orsholms Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Per Knutsson Vistakullefruktodling', NOW());
insert into suppliers(name, created_at) values('Red & White AB', NOW());
insert into suppliers(name, created_at) values('ICS Trading HB', NOW());
insert into suppliers(name, created_at) values('Renards Import AB', NOW());
insert into suppliers(name, created_at) values('Brasri AB', NOW());
insert into suppliers(name, created_at) values('Hopsan Brewing AB', NOW());
insert into suppliers(name, created_at) values('Vin Drumlin AB', NOW());
insert into suppliers(name, created_at) values('AB No.1 Production', NOW());
insert into suppliers(name, created_at) values('Vinitor AB', NOW());
insert into suppliers(name, created_at) values('Agrell & Hartley Selection AB', NOW());
insert into suppliers(name, created_at) values('Beverage Market of Scandinavia AB', NOW());
insert into suppliers(name, created_at) values('RajRaj Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Suttungs Bryggeri', NOW());
insert into suppliers(name, created_at) values('Niscada International AB', NOW());
insert into suppliers(name, created_at) values('Köpings Musteri AB', NOW());
insert into suppliers(name, created_at) values('Jämmerdalen Hantverksbryggeri Handelsbolag', NOW());
insert into suppliers(name, created_at) values('Kaj Nilsson', NOW());
insert into suppliers(name, created_at) values('Bier & Co Sweden AB', NOW());
insert into suppliers(name, created_at) values('Philipson Söderberg AB', NOW());
insert into suppliers(name, created_at) values('Wine Waves', NOW());
insert into suppliers(name, created_at) values('Beer & Spiritpartners Nordic AB', NOW());
insert into suppliers(name, created_at) values('Allegresse AB', NOW());
insert into suppliers(name, created_at) values('Northern Beverages AB', NOW());
insert into suppliers(name, created_at) values('Sparkling collection by J&M AB', NOW());
insert into suppliers(name, created_at) values('Panache Sweden AB', NOW());
insert into suppliers(name, created_at) values('Portucastas AB', NOW());
insert into suppliers(name, created_at) values('Jack Barlows Wine AB', NOW());
insert into suppliers(name, created_at) values('NBI i Växjö AB', NOW());
insert into suppliers(name, created_at) values('Bryggeriet Stenhammaren AB', NOW());
insert into suppliers(name, created_at) values('Winberg & Partner AB', NOW());
insert into suppliers(name, created_at) values('KronUgglan Handelsbolag', NOW());
insert into suppliers(name, created_at) values('Snausarve Gårdsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Fredholms Vin', NOW());
insert into suppliers(name, created_at) values('Business Monkey Brewing AB', NOW());
insert into suppliers(name, created_at) values('Scanwine of Sweden AB', NOW());
insert into suppliers(name, created_at) values('Svanshals Brygghus AB', NOW());
insert into suppliers(name, created_at) values('Sam & Jenny Wine & Food', NOW());
insert into suppliers(name, created_at) values('Caffe Olivedal AB', NOW());
insert into suppliers(name, created_at) values('Husaren Bryggeri Aktiebolag', NOW());
insert into suppliers(name, created_at) values('Selected Malts Barkevall Westerberg AB', NOW());
insert into suppliers(name, created_at) values('Lucky Ones Wines and Beers Import HB', NOW());
insert into suppliers(name, created_at) values('Words & Wines AB', NOW());
insert into suppliers(name, created_at) values('Åhus Bryggeri Anno 1900', NOW());
insert into suppliers(name, created_at) values('Bråhovda Drinks AB', NOW());
insert into suppliers(name, created_at) values('Malmö Brewing AB', NOW());
insert into suppliers(name, created_at) values('Sollentuna Bryggeri', NOW());
insert into suppliers(name, created_at) values('En Aleigen Brewery', NOW());
insert into suppliers(name, created_at) values('Cedentolin AB', NOW());
insert into suppliers(name, created_at) values('Västergården Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Wittja Brygghus AB', NOW());
insert into suppliers(name, created_at) values('The Wine Collection Sweden Holding AB', NOW());
insert into suppliers(name, created_at) values('Agent Clay AB', NOW());
insert into suppliers(name, created_at) values('Neptunium AB', NOW());
insert into suppliers(name, created_at) values('Olito Vin Handelsbolag', NOW());
insert into suppliers(name, created_at) values('The Odd House Brewing Company AB', NOW());
insert into suppliers(name, created_at) values('Brooklyn Stockholm OpCo AB', NOW());
insert into suppliers(name, created_at) values('Dryck STHLM AB', NOW());
insert into suppliers(name, created_at) values('Smögen Whisky AB', NOW());
insert into suppliers(name, created_at) values('Backman Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Amazing Wines Hedberg & Wising AB', NOW());
insert into suppliers(name, created_at) values('PR Trot & Trade AB', NOW());
insert into suppliers(name, created_at) values('Norrlands Fruktvin AB', NOW());
insert into suppliers(name, created_at) values('Varberg Beerworks AB', NOW());
insert into suppliers(name, created_at) values('1868 Group AB', NOW());
insert into suppliers(name, created_at) values('Handelsbolaget Guideline Wines', NOW());
insert into suppliers(name, created_at) values('Johan Hagström & Co HAB', NOW());
insert into suppliers(name, created_at) values('Baccus Vinhandel i Mora AB', NOW());
insert into suppliers(name, created_at) values('Hydmar AB', NOW());
insert into suppliers(name, created_at) values('Scandinavian Hub AB', NOW());
insert into suppliers(name, created_at) values('Distillery & Spirits of Lapland AB', NOW());
insert into suppliers(name, created_at) values('H.A.R.R.E.L AB', NOW());
insert into suppliers(name, created_at) values('Sweden Spirit Group AB', NOW());
insert into suppliers(name, created_at) values('Säröbanans Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('DaiFratelliWine AB', NOW());
insert into suppliers(name, created_at) values('Hybris AB', NOW());
insert into suppliers(name, created_at) values('Gröna Linjen Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Norrbottens Destilleri AB', NOW());
insert into suppliers(name, created_at) values('Prodedge Filial', NOW());
insert into suppliers(name, created_at) values('AB Östersjö Vodka', NOW());
insert into suppliers(name, created_at) values('Nordic Beverage Company AB', NOW());
insert into suppliers(name, created_at) values('Stallarholmens brygghus AB', NOW());
insert into suppliers(name, created_at) values('Spriteriet AB', NOW());
insert into suppliers(name, created_at) values('Qvarnens AB', NOW());
insert into suppliers(name, created_at) values('Två Liljor AB', NOW());
insert into suppliers(name, created_at) values('Brygg3an i Halmstad AB', NOW());
insert into suppliers(name, created_at) values('The Piraya Brewery AB', NOW());
insert into suppliers(name, created_at) values('Vilda Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Berners Mat och Vinklubb AB', NOW());
insert into suppliers(name, created_at) values('Rospart Holding AB', NOW());
insert into suppliers(name, created_at) values('Sour & Wine AB', NOW());
insert into suppliers(name, created_at) values('Arbore Ab', NOW());
insert into suppliers(name, created_at) values('Hoff Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Invini AB', NOW());
insert into suppliers(name, created_at) values('Ceylon Wines & Co. AB', NOW());
insert into suppliers(name, created_at) values('Klocktornet Destilleri AB', NOW());
insert into suppliers(name, created_at) values('Björknäs Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Sincere Wines AB', NOW());
insert into suppliers(name, created_at) values('Taste Port Gothenburg AB', NOW());
insert into suppliers(name, created_at) values('Wine4U i Finspång AB', NOW());
insert into suppliers(name, created_at) values('Wine Shack AB', NOW());
insert into suppliers(name, created_at) values('SAV Winery AB (publ)', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Occivins', NOW());
insert into suppliers(name, created_at) values('Rosforth & Rosforth AB', NOW());
insert into suppliers(name, created_at) values('WineTastic Sweden AB', NOW());
insert into suppliers(name, created_at) values('Exoro Wine Import AB', NOW());
insert into suppliers(name, created_at) values('Acid Wines Stockholm Handelsbolag', NOW());
insert into suppliers(name, created_at) values('WeBrew Brewing AB', NOW());
insert into suppliers(name, created_at) values('Elisa Vin AB', NOW());
insert into suppliers(name, created_at) values('Tjärnsjö Brewery', NOW());
insert into suppliers(name, created_at) values('Glabo Gårdsbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Exermans Bryggeri', NOW());
insert into suppliers(name, created_at) values('Viboe Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Kesuddens Konsult AB', NOW());
insert into suppliers(name, created_at) values('Vinkollektivet AB', NOW());
insert into suppliers(name, created_at) values('Två Små Svin/Nygren Catering & Event HB', NOW());
insert into suppliers(name, created_at) values('Hernö Gin AB', NOW());
insert into suppliers(name, created_at) values('Skogens Sköna Gröna AB', NOW());
insert into suppliers(name, created_at) values('Lakeside Brewery', NOW());
insert into suppliers(name, created_at) values('Hawelkas Brewing Company AB', NOW());
insert into suppliers(name, created_at) values('Wilderness Brewery AB', NOW());
insert into suppliers(name, created_at) values('Illbatting Brewing HB', NOW());
insert into suppliers(name, created_at) values('Vinolin AB', NOW());
insert into suppliers(name, created_at) values('Nova Handel i Göteborg AB', NOW());
insert into suppliers(name, created_at) values('Hellström Gin AB', NOW());
insert into suppliers(name, created_at) values('I.C.E Vodka of Sweden AB', NOW());
insert into suppliers(name, created_at) values('OM.DuoVin AB', NOW());
insert into suppliers(name, created_at) values('KON Beverages AB', NOW());
insert into suppliers(name, created_at) values('S by Jorge', NOW());
insert into suppliers(name, created_at) values('Bevono Beverages AB', NOW());
insert into suppliers(name, created_at) values('Lydén Distillery AB', NOW());
insert into suppliers(name, created_at) values('Raïm vinimport handelsbolag', NOW());
insert into suppliers(name, created_at) values('Unibärsum AB', NOW());
insert into suppliers(name, created_at) values('Vuxenpedagogisk Konsultation i Linköping AB', NOW());
insert into suppliers(name, created_at) values('Frillestads Vingård HB', NOW());
insert into suppliers(name, created_at) values('Pilsnerimporten Englesson och Axen AB', NOW());
insert into suppliers(name, created_at) values('Nordisk Drama & Dokumentär AB', NOW());
insert into suppliers(name, created_at) values('None', NOW());
insert into suppliers(name, created_at) values('BrewOre AB', NOW());
insert into suppliers(name, created_at) values('Sodafactory Stockholm AB', NOW());
insert into suppliers(name, created_at) values('Yellow Eye Spirits AB', NOW());
insert into suppliers(name, created_at) values('ALWines Sweden AB', NOW());
insert into suppliers(name, created_at) values('RekoVin Sverige AB', NOW());
insert into suppliers(name, created_at) values('Blomdell C&M AB', NOW());
insert into suppliers(name, created_at) values('JAGA Solutions AB', NOW());
insert into suppliers(name, created_at) values('Segerstrom Wines AB', NOW());
insert into suppliers(name, created_at) values('Avenue wines AB', NOW());
insert into suppliers(name, created_at) values('Köpingsbergs Gård AB', NOW());
insert into suppliers(name, created_at) values('Home Studio Revsund HB', NOW());
insert into suppliers(name, created_at) values('AB Wolkes Punsch', NOW());
insert into suppliers(name, created_at) values('Jönköpings Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Tumi AB', NOW());
insert into suppliers(name, created_at) values('Cesarino Gobbi', NOW());
insert into suppliers(name, created_at) values('Heavy MetAle AB', NOW());
insert into suppliers(name, created_at) values('Skebo Bruksbryggeri ekonomisk förening', NOW());
insert into suppliers(name, created_at) values('H3 Systems AB', NOW());
insert into suppliers(name, created_at) values('Plivit Trade AB', NOW());
insert into suppliers(name, created_at) values('Gripsholm Distillery AB', NOW());
insert into suppliers(name, created_at) values('China Trading i Stockholm AB', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Mat & Dryck i Stockholm', NOW());
insert into suppliers(name, created_at) values('Lindvino', NOW());
insert into suppliers(name, created_at) values('Just Brands in Sweden AB', NOW());
insert into suppliers(name, created_at) values('Gullyckevin och konsult', NOW());
insert into suppliers(name, created_at) values('Särtshöga Vingård AB', NOW());
insert into suppliers(name, created_at) values('Holavedens Handel Hus Ek för', NOW());
insert into suppliers(name, created_at) values('Mercura Sweden AB', NOW());
insert into suppliers(name, created_at) values('Stragas-Gruppen AB', NOW());
insert into suppliers(name, created_at) values('Shotluckan Holding AB', NOW());
insert into suppliers(name, created_at) values('WSB The Beverage Company AB', NOW());
insert into suppliers(name, created_at) values('UNIQ Handelsbolag', NOW());
insert into suppliers(name, created_at) values('Pr. Estige Spirits AB', NOW());
insert into suppliers(name, created_at) values('ZNAPS Sweden AB', NOW());
insert into suppliers(name, created_at) values('Urban Beverages AB', NOW());
insert into suppliers(name, created_at) values('Magnum Wine AB', NOW());
insert into suppliers(name, created_at) values('Ribes Nigrum Vingård AB', NOW());
insert into suppliers(name, created_at) values('Solsidans Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Ekjord Sweden AB', NOW());
insert into suppliers(name, created_at) values('Supreme Wine & Spirit AB', NOW());
insert into suppliers(name, created_at) values('Vinum Veritas Wine Agency AB', NOW());
insert into suppliers(name, created_at) values('Sörby Vinhandel AB', NOW());
insert into suppliers(name, created_at) values('Stora Bryne Vin & Trädgård', NOW());
insert into suppliers(name, created_at) values('C & E Gastro-Import AB', NOW());
insert into suppliers(name, created_at) values('Adelsö Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('CHill Creek AB', NOW());
insert into suppliers(name, created_at) values('Georg Strömfelt', NOW());
insert into suppliers(name, created_at) values('Carlberg Vinhus AB', NOW());
insert into suppliers(name, created_at) values('Toivio Innovation AB', NOW());
insert into suppliers(name, created_at) values('Karl Källander', NOW());
insert into suppliers(name, created_at) values('Habibi Stockholm AB', NOW());
insert into suppliers(name, created_at) values('Mestej', NOW());
insert into suppliers(name, created_at) values('FC Bryggeri AB', NOW());
insert into suppliers(name, created_at) values('Mats Carlsson Reklambyrå Nordic Wine Company', NOW());
insert into suppliers(name, created_at) values('Gute Bryggeri', NOW());
insert into suppliers(name, created_at) values('Vinupplevelser i Sverige AB', NOW());
insert into suppliers(name, created_at) values('Österlenvin HB', NOW());
insert into suppliers(name, created_at) values('New Brews Sweden AB', NOW());
insert into suppliers(name, created_at) values('Classic Wine Sweden AB', NOW());
insert into suppliers(name, created_at) values('Dunder & Krut AB', NOW());
insert into suppliers(name, created_at) values('Modern Wines Sweden AB', NOW());
insert into suppliers(name, created_at) values('Sundell Selections AB', NOW());
insert into suppliers(name, created_at) values('Nygrens Hyrservice', NOW());
insert into suppliers(name, created_at) values('Bevgru AB', NOW());
insert into suppliers(name, created_at) values('Vinumlux', NOW());
insert into suppliers(name, created_at) values('SSARK Maltbryggeri AB', NOW());
insert into suppliers(name, created_at) values('Vinlusen AB', NOW());
insert into suppliers(name, created_at) values('Aktiebolaget Gbg Soda', NOW());
insert into suppliers(name, created_at) values('Laitilan Svenska Filial', NOW());
