insert into suppliers(name, created_at) values('Pernod Ricard Sweden AB', now());
insert into suppliers(name, created_at) values('Vinoliv Import AB', now());
insert into suppliers(name, created_at) values('High Coast Wine AB', now());
insert into suppliers(name, created_at) values('Imperiebryggeriet  AB', now());
insert into suppliers(name, created_at) values('Fine Brands Sweden AB', now());
insert into suppliers(name, created_at) values('Dryckesboden Sverige AB', now());
insert into suppliers(name, created_at) values('CCS AB', now());
insert into suppliers(name, created_at) values('Sybaris - Wine & Spirits AB', now());
insert into suppliers(name, created_at) values('Aktiebolaget Roslags Näsby Bryggeri', now());
insert into suppliers(name, created_at) values('Arcus Sweden AB', now());
insert into suppliers(name, created_at) values('Skelderwikens Brygghus AB', now());
insert into suppliers(name, created_at) values('Halmstad Brygghus AB', now());
insert into suppliers(name, created_at) values('Fjäderholmarnas Bryggeri AB', now());
insert into suppliers(name, created_at) values('We & Wine AB', now());
insert into suppliers(name, created_at) values('Restaurang Skeppsgossen AB', now());
insert into suppliers(name, created_at) values('South Plains Brewing Company', now());
insert into suppliers(name, created_at) values('Granqvist Beverage House AB', now());
insert into suppliers(name, created_at) values('Vinobele AB', now());
insert into suppliers(name, created_at) values('Spendrups Bryggeri AB', now());
insert into suppliers(name, created_at) values('AliasSmith AB', now());
insert into suppliers(name, created_at) values('Fields Wine Company AB', now());
insert into suppliers(name, created_at) values('Clydesdale AB', now());
insert into suppliers(name, created_at) values('Chris-Wine AB', now());
insert into suppliers(name, created_at) values('O.Wines and Spirits AB', now());
insert into suppliers(name, created_at) values('janake wine group AB', now());
insert into suppliers(name, created_at) values('Mackmyra Svensk Whisky AB', now());
insert into suppliers(name, created_at) values('Ward Wines AB', now());
insert into suppliers(name, created_at) values('The Wine Collection Sweden AB', now());
insert into suppliers(name, created_at) values('Johan Lidby Vinhandel AB', now());
insert into suppliers(name, created_at) values('Lancel AB', now());
insert into suppliers(name, created_at) values('Vinunic AB', now());
insert into suppliers(name, created_at) values('Giertz Vinimport AB', now());
insert into suppliers(name, created_at) values('The WineAgency Sweden AB', now());
insert into suppliers(name, created_at) values('Brands For Fans Sweden AB', now());
insert into suppliers(name, created_at) values('Hermansson & Co AB', now());
insert into suppliers(name, created_at) values('Skrubbes Wines AB', now());
insert into suppliers(name, created_at) values('Divine AB', now());
insert into suppliers(name, created_at) values('Enrico Sverige AB', now());
insert into suppliers(name, created_at) values('Tevsjö Destilleri i Järvsö AB', now());
insert into suppliers(name, created_at) values('Carovin AB', now());
insert into suppliers(name, created_at) values('Wine Lounge Stockholm AB', now());
insert into suppliers(name, created_at) values('Robert Rask Vinhandel', now());
insert into suppliers(name, created_at) values('Arvid Nordquist Vin och Sprithandel', now());
insert into suppliers(name, created_at) values('Great Brands AB', now());
insert into suppliers(name, created_at) values('TOMP Beer Wine & Spirits AB', now());
insert into suppliers(name, created_at) values('TM Kvalitetsviner AB', now());
insert into suppliers(name, created_at) values('Vivona AB', now());
insert into suppliers(name, created_at) values('Intermondi AB', now());
insert into suppliers(name, created_at) values('Altia Sweden AB', now());
insert into suppliers(name, created_at) values('Brewing Költur AB', now());
insert into suppliers(name, created_at) values('Oenoforos AB', now());
insert into suppliers(name, created_at) values('Rådanäs Bryggeri AB', now());
insert into suppliers(name, created_at) values('Svensk Cater AB', now());
insert into suppliers(name, created_at) values('Sigva AB', now());
insert into suppliers(name, created_at) values('Brewify AB', now());
insert into suppliers(name, created_at) values('Handpicked Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Winepartners Nordic AB', now());
insert into suppliers(name, created_at) values('Spivi AB', now());
insert into suppliers(name, created_at) values('Malchamax AB', now());
insert into suppliers(name, created_at) values('Cask Sweden AB', now());
insert into suppliers(name, created_at) values('Anno 1953 AB', now());
insert into suppliers(name, created_at) values('Mondo Wine Sweden AB', now());
insert into suppliers(name, created_at) values('Galatea AB', now());
insert into suppliers(name, created_at) values('Grythyttan Vin', now());
insert into suppliers(name, created_at) values('Åbro Bryggeri', now());
insert into suppliers(name, created_at) values('Asahi Sweden Filial', now());
insert into suppliers(name, created_at) values('Vinovativa AB', now());
insert into suppliers(name, created_at) values('Stellan Kramer AB', now());
insert into suppliers(name, created_at) values('ClosProbus KB', now());
insert into suppliers(name, created_at) values('Picky Drinks AB', now());
insert into suppliers(name, created_at) values('Dugges Bryggeri AB', now());
insert into suppliers(name, created_at) values('Nils Oscar AB', now());
insert into suppliers(name, created_at) values('WineWorld AB', now());
insert into suppliers(name, created_at) values('Carlsberg Sverige AB', now());
insert into suppliers(name, created_at) values('Vingården Bacina AB', now());
insert into suppliers(name, created_at) values('Samplex AB', now());
insert into suppliers(name, created_at) values('Triggollo Wine & Spirits AB', now());
insert into suppliers(name, created_at) values('Quaffable Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Brandpartners AB', now());
insert into suppliers(name, created_at) values('Amka Vinimport AB', now());
insert into suppliers(name, created_at) values('Iconic Wines', now());
insert into suppliers(name, created_at) values('Moestue Grape Selections AB', now());
insert into suppliers(name, created_at) values('Brill & Co AB', now());
insert into suppliers(name, created_at) values('Lapland Water AB', now());
insert into suppliers(name, created_at) values('Domaine Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Brewery International Sweden AB', now());
insert into suppliers(name, created_at) values('Viña Española AB', now());
insert into suppliers(name, created_at) values('Bibendum', now());
insert into suppliers(name, created_at) values('Diageo Sweden AB', now());
insert into suppliers(name, created_at) values('Enjoy Wine & Spirits AB', now());
insert into suppliers(name, created_at) values('Provinum Vinhandel AB', now());
insert into suppliers(name, created_at) values('Vinestor Sweden AB', now());
insert into suppliers(name, created_at) values('Jakobsson och Söderström AB', now());
insert into suppliers(name, created_at) values('Prime Wine Sweden AB', now());
insert into suppliers(name, created_at) values('Ametller Scandinavia - spanska produkter AB', now());
insert into suppliers(name, created_at) values('Terrific Wines AB', now());
insert into suppliers(name, created_at) values('Vega Bryggeri AB', now());
insert into suppliers(name, created_at) values('Contemporary wines Sweden AB', now());
insert into suppliers(name, created_at) values('Alingsås Bryggeri AB', now());
insert into suppliers(name, created_at) values('Åsalid Design', now());
insert into suppliers(name, created_at) values('Bornicon & Salming', now());
insert into suppliers(name, created_at) values('Valkyria Distillery AB', now());
insert into suppliers(name, created_at) values('Carlskrona Bryggeri AB', now());
insert into suppliers(name, created_at) values('Villa Aurum AB', now());
insert into suppliers(name, created_at) values('Premier Taste Sweden AB', now());
insert into suppliers(name, created_at) values('Vinia Sweden AB', now());
insert into suppliers(name, created_at) values('Jädraås Bryggeri AB', now());
insert into suppliers(name, created_at) values('Nacka Bryggeri AB', now());
insert into suppliers(name, created_at) values('Qvänum Mat & Malt AB', now());
insert into suppliers(name, created_at) values('Systembolaget Presenter', now());
insert into suppliers(name, created_at) values('Leufstabruk Bryggeri AB', now());
insert into suppliers(name, created_at) values('Pikulik, Peter', now());
insert into suppliers(name, created_at) values('Henkell Freixenet Sweden AB', now());
insert into suppliers(name, created_at) values('Bonne Box / Ett Ord AB', now());
insert into suppliers(name, created_at) values('Nelex Beverage AB', now());
insert into suppliers(name, created_at) values('Theis Vine AB', now());
insert into suppliers(name, created_at) values('Carlemår Wine & Spirits AB', now());
insert into suppliers(name, created_at) values('Wine Affair Scandinavia AB', now());
insert into suppliers(name, created_at) values('Risotto Fine Foods & Wine', now());
insert into suppliers(name, created_at) values('Nigab', now());
insert into suppliers(name, created_at) values('Kämpinge Trading AB', now());
insert into suppliers(name, created_at) values('World Beer Trading KB', now());
insert into suppliers(name, created_at) values('AB Wicked Wine Sweden', now());
insert into suppliers(name, created_at) values('Runa Vodka AB', now());
insert into suppliers(name, created_at) values('Apricot AB', now());
insert into suppliers(name, created_at) values('Buteljholmen AB', now());
insert into suppliers(name, created_at) values('Tre Svampar AB', now());
insert into suppliers(name, created_at) values('Vinonista AB', now());
insert into suppliers(name, created_at) values('Nebbia HB', now());
insert into suppliers(name, created_at) values('Jämtlands Bryggeri AB', now());
insert into suppliers(name, created_at) values('Winemarket Nordic AB', now());
insert into suppliers(name, created_at) values('Grapestyle Scandinavia', now());
insert into suppliers(name, created_at) values('Vintedge AB', now());
insert into suppliers(name, created_at) values('RB Winery AB', now());
insert into suppliers(name, created_at) values('Mjödhamnen AB', now());
insert into suppliers(name, created_at) values('Dica Vin & Sprit HB', now());
insert into suppliers(name, created_at) values('Swedish Brand AB', now());
insert into suppliers(name, created_at) values('The Wine and Spirits Collective Sweden AB', now());
insert into suppliers(name, created_at) values('Vänersborgs Vinagentur AB', now());
insert into suppliers(name, created_at) values('Valid Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Herida Aurum AB', now());
insert into suppliers(name, created_at) values('Triplus Vinhandel AB', now());
insert into suppliers(name, created_at) values('Waxholms Bryggeri AB', now());
insert into suppliers(name, created_at) values('GodDryck i Sverige AB', now());
insert into suppliers(name, created_at) values('Wine Group Sweden AB', now());
insert into suppliers(name, created_at) values('Winebee AB', now());
insert into suppliers(name, created_at) values('Corseimport', now());
insert into suppliers(name, created_at) values('Hjo Grosshandel AB', now());
insert into suppliers(name, created_at) values('Värmdö Bränneri AB', now());
insert into suppliers(name, created_at) values('Sundance Wines AB', now());
insert into suppliers(name, created_at) values('Krates Vin & Delikatesser', now());
insert into suppliers(name, created_at) values('Vino Conoscenza AB', now());
insert into suppliers(name, created_at) values('Cask Kompaniet AB', now());
insert into suppliers(name, created_at) values('People Wine AB', now());
insert into suppliers(name, created_at) values('Flying Brewery AB', now());
insert into suppliers(name, created_at) values('Greenery Wines KB', now());
insert into suppliers(name, created_at) values('Viness AB', now());
insert into suppliers(name, created_at) values('AB Svenska Sprit TBH', now());
insert into suppliers(name, created_at) values('Skellefteå Bryggeri AB', now());
insert into suppliers(name, created_at) values('LarCap AB', now());
insert into suppliers(name, created_at) values('Remilio AB', now());
insert into suppliers(name, created_at) values('Hard On AB', now());
insert into suppliers(name, created_at) values('Edrington Sweden AB', now());
insert into suppliers(name, created_at) values('Gullberg by Stockwine AB', now());
insert into suppliers(name, created_at) values('AB Brygghuset Finn', now());
insert into suppliers(name, created_at) values('Remmarlöv Gårdsbryggeri AB', now());
insert into suppliers(name, created_at) values('Grebbestad Bryggeri AB', now());
insert into suppliers(name, created_at) values('Södra Maltfabriken AB', now());
insert into suppliers(name, created_at) values('Best Of Special Selected Wine AB', now());
insert into suppliers(name, created_at) values('Bristly Wine Agents AB', now());
insert into suppliers(name, created_at) values('Viniverdi Sweden AB', now());
insert into suppliers(name, created_at) values('Närke Kulturbryggeri AB', now());
insert into suppliers(name, created_at) values('Kackelstugan AB', now());
insert into suppliers(name, created_at) values('Kiviks Musteri AB', now());
insert into suppliers(name, created_at) values('Barkonsult Jakobsson & Lövgren AB', now());
insert into suppliers(name, created_at) values('Treasury Wine Estates Sweden AB', now());
insert into suppliers(name, created_at) values('Fulltofta Gårdsbryggeri AB', now());
insert into suppliers(name, created_at) values('Doriani Wines AB', now());
insert into suppliers(name, created_at) values('Speedy Wine Store AB', now());
insert into suppliers(name, created_at) values('Rewine AB', now());
insert into suppliers(name, created_at) values('Smaken av Piemonte AB', now());
insert into suppliers(name, created_at) values('The Wine Team Global AB', now());
insert into suppliers(name, created_at) values('Brygghus 19 AB', now());
insert into suppliers(name, created_at) values('Sapordivino Sweden AB', now());
insert into suppliers(name, created_at) values('Sigva Partner AB', now());
insert into suppliers(name, created_at) values('Symposion AB', now());
insert into suppliers(name, created_at) values('ChampagneExperten by Västerås Sweden HB', now());
insert into suppliers(name, created_at) values('Happy Dog Dryckeshandel AB', now());
insert into suppliers(name, created_at) values('Juvinum Wine, Beer & Spirits AB', now());
insert into suppliers(name, created_at) values('VCT Sweden AB', now());
insert into suppliers(name, created_at) values('Moët Hennessy Sverige AB', now());
insert into suppliers(name, created_at) values('Nääs gårdsbryggeri', now());
insert into suppliers(name, created_at) values('Värmdö Bryggeri AB', now());
insert into suppliers(name, created_at) values('Walhöll Brygghus', now());
insert into suppliers(name, created_at) values('Sälens Fjällbryggeri AB', now());
insert into suppliers(name, created_at) values('Råå Bryggeri AB', now());
insert into suppliers(name, created_at) values('Facile & Co AB', now());
insert into suppliers(name, created_at) values('Coppersmith AB', now());
insert into suppliers(name, created_at) values('Auld Rare Whisky Sweden AB', now());
insert into suppliers(name, created_at) values('Kasper Schönhult AB (Charlis Brygghus)', now());
insert into suppliers(name, created_at) values('Berntson Brands AB', now());
insert into suppliers(name, created_at) values('Sture Spirit AB', now());
insert into suppliers(name, created_at) values('Svenska Vinkompaniet', now());
insert into suppliers(name, created_at) values('Smaksinnet AB', now());
insert into suppliers(name, created_at) values('Zebrawine i Uppsala AB', now());
insert into suppliers(name, created_at) values('Principium Dryck AB', now());
insert into suppliers(name, created_at) values('Avivera AB', now());
insert into suppliers(name, created_at) values('ExpertWine Naturvin AB', now());
insert into suppliers(name, created_at) values('Kopparbergs Bryggeri AB', now());
insert into suppliers(name, created_at) values('Vintrio Wine AB', now());
insert into suppliers(name, created_at) values('Les Millésimes HB', now());
insert into suppliers(name, created_at) values('Conveija Aktiebolag', now());
insert into suppliers(name, created_at) values('Alshammar Import', now());
insert into suppliers(name, created_at) values('Verissima AB', now());
insert into suppliers(name, created_at) values('Brix Wine Consultants AB', now());
insert into suppliers(name, created_at) values('Skepparps Vingård', now());
insert into suppliers(name, created_at) values('Lively Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Vinovum AB', now());
insert into suppliers(name, created_at) values('Fine Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Dalelven Holding AB', now());
insert into suppliers(name, created_at) values('Ofwerman Imports AB', now());
insert into suppliers(name, created_at) values('2Goda Vin & Bryggeri', now());
insert into suppliers(name, created_at) values('Nippon Sake Sweden AB', now());
insert into suppliers(name, created_at) values('Fisherstorm Filial til Berentsens Brygghus AS Norway', now());
insert into suppliers(name, created_at) values('Ahlafors Bryggerier AB', now());
insert into suppliers(name, created_at) values('Aktiebolaget Centralbryggeriet i Linköping', now());
insert into suppliers(name, created_at) values('Sibbarps Husbryggeri AB', now());
insert into suppliers(name, created_at) values('Concealed Wines AB', now());
insert into suppliers(name, created_at) values('Independent Wine Company AB', now());
insert into suppliers(name, created_at) values('Bryggeriaktiebolaget Nya Victoria', now());
insert into suppliers(name, created_at) values('Origo Wine Import', now());
insert into suppliers(name, created_at) values('Pite Bryggeri AB', now());
insert into suppliers(name, created_at) values('VinTillMat i Väst AB', now());
insert into suppliers(name, created_at) values('The Beer Factory Leksand AB', now());
insert into suppliers(name, created_at) values('Roslagens Brygghus AB', now());
insert into suppliers(name, created_at) values('UP Wine', now());
insert into suppliers(name, created_at) values('Mission Wine & Spirit AB', now());
insert into suppliers(name, created_at) values('Wermlands Brygghus AB', now());
insert into suppliers(name, created_at) values('Beer Me Sweden AB', now());
insert into suppliers(name, created_at) values('Jackdaw Brewery AB', now());
insert into suppliers(name, created_at) values('Poppels Bryggeri AB', now());
insert into suppliers(name, created_at) values('Nordmarkens Destilleri AB', now());
insert into suppliers(name, created_at) values('Snickerivägens bryggeri AB', now());
insert into suppliers(name, created_at) values('Wembrands World AB', now());
insert into suppliers(name, created_at) values('Ludvig Sääf', now());
insert into suppliers(name, created_at) values('VinoNovo AB', now());
insert into suppliers(name, created_at) values('Gamla Slottskällans Bryggeri AB', now());
insert into suppliers(name, created_at) values('AB Hantverksöl Gamla Enskede', now());
insert into suppliers(name, created_at) values('Renbjer & Magnusson AB', now());
insert into suppliers(name, created_at) values('Vendemmia Vinimport AB', now());
insert into suppliers(name, created_at) values('Ocean Brewery AB', now());
insert into suppliers(name, created_at) values('Multibev AB', now());
insert into suppliers(name, created_at) values('Sofrakis Murat', now());
insert into suppliers(name, created_at) values('Klackabackens bryggeri AB', now());
insert into suppliers(name, created_at) values('Kaffak AB', now());
insert into suppliers(name, created_at) values('Wannborga på Öland AB', now());
insert into suppliers(name, created_at) values('Bålsta Bryggeri AB', now());
insert into suppliers(name, created_at) values('Ysäter AB', now());
insert into suppliers(name, created_at) values('Tuesday Wine AB', now());
insert into suppliers(name, created_at) values('Michael Malmbom', now());
insert into suppliers(name, created_at) values('Uppsala Brygghus AB', now());
insert into suppliers(name, created_at) values('Sahlins Brygghus AB', now());
insert into suppliers(name, created_at) values('Viken Bryggeri AB', now());
insert into suppliers(name, created_at) values('Wapnö AB', now());
insert into suppliers(name, created_at) values('Brewtrade Sweden AB', now());
insert into suppliers(name, created_at) values('Sundbybergs köksbryggeri AB', now());
insert into suppliers(name, created_at) values('Västra Ämterviks Bryggeri AB', now());
insert into suppliers(name, created_at) values('Härjedalens bryggeriaktiebolag', now());
insert into suppliers(name, created_at) values('Carlstad bryggeri KB', now());
insert into suppliers(name, created_at) values('Modernist Brewery AB', now());
insert into suppliers(name, created_at) values('Selected French Wine Nordic HB', now());
insert into suppliers(name, created_at) values('Old Cowhouse Brewery AB', now());
insert into suppliers(name, created_at) values('Götene Vin & Spritfabrik AB', now());
insert into suppliers(name, created_at) values('Whiskytaste Sweden AB', now());
insert into suppliers(name, created_at) values('Bacardi AB', now());
insert into suppliers(name, created_at) values('Rhuby AB', now());
insert into suppliers(name, created_at) values('Nice Wine i Jönköping AB', now());
insert into suppliers(name, created_at) values('Fiskebäcksbryggeriet AB', now());
insert into suppliers(name, created_at) values('Netterberg & Co AB', now());
insert into suppliers(name, created_at) values('Den Bryggande Holländaren AB', now());
insert into suppliers(name, created_at) values('Limhamns Bryggeri', now());
insert into suppliers(name, created_at) values('Örebro Brygghus i Nerike AB', now());
insert into suppliers(name, created_at) values('Skånska Spritfabriken', now());
insert into suppliers(name, created_at) values('Euroway Airline', now());
insert into suppliers(name, created_at) values('Fors Bryggeri KB', now());
insert into suppliers(name, created_at) values('Selbac AB', now());
insert into suppliers(name, created_at) values('Meadow Valley Wines', now());
insert into suppliers(name, created_at) values('Orbaden Zip & Climb AB', now());
insert into suppliers(name, created_at) values('Albert&Lily AB', now());
insert into suppliers(name, created_at) values('Vini Buoni AB', now());
insert into suppliers(name, created_at) values('U and Me Beer AB', now());
insert into suppliers(name, created_at) values('Bryggverket AB', now());
insert into suppliers(name, created_at) values('Beer Studio AB', now());
insert into suppliers(name, created_at) values('Emmaboda Bryggeri AB', now());
insert into suppliers(name, created_at) values('Ferna Forge Brewery AB', now());
insert into suppliers(name, created_at) values('Nora Brygghus AB', now());
insert into suppliers(name, created_at) values('Bergslagens Destilleri Örebro AB', now());
insert into suppliers(name, created_at) values('Alskute Farm & Brewery AB', now());
insert into suppliers(name, created_at) values('Joyride Wine', now());
insert into suppliers(name, created_at) values('Hemberga Dryckesgrossisten AB', now());
insert into suppliers(name, created_at) values('Göteborgs Vinhandelshus AB', now());
insert into suppliers(name, created_at) values('JPC Wines AB', now());
insert into suppliers(name, created_at) values('Båstad Wine & Champagne AB', now());
insert into suppliers(name, created_at) values('Liquorama AB', now());
insert into suppliers(name, created_at) values('Helsingborgs Bryggeri AB', now());
insert into suppliers(name, created_at) values('GPS Good Public Spirit AB', now());
insert into suppliers(name, created_at) values('Saturnus', now());
insert into suppliers(name, created_at) values('Norrtelje Brenneri AB', now());
insert into suppliers(name, created_at) values('Winehouse Bilberg', now());
insert into suppliers(name, created_at) values('Cantina del Re HB', now());
insert into suppliers(name, created_at) values('E&E Wine / Pamela Lundin', now());
insert into suppliers(name, created_at) values('Hults Dryck & Delikatess AB', now());
insert into suppliers(name, created_at) values('Elixir HB', now());
insert into suppliers(name, created_at) values('Vinopia Wine & Spirit AB', now());
insert into suppliers(name, created_at) values('VinBistro Stockholm AB', now());
insert into suppliers(name, created_at) values('Zemela Wines AB', now());
insert into suppliers(name, created_at) values('Omnipollo AB', now());
insert into suppliers(name, created_at) values('Möllys AB', now());
insert into suppliers(name, created_at) values('MakarnaSvärd', now());
insert into suppliers(name, created_at) values('Göteborgs Nya Bryggeri AB', now());
insert into suppliers(name, created_at) values('Alnöl AB', now());
insert into suppliers(name, created_at) values('Höganäs Bryggeri AB', now());
insert into suppliers(name, created_at) values('Pax Brygghus AB', now());
insert into suppliers(name, created_at) values('Lobia AB', now());
insert into suppliers(name, created_at) values('Scandinavian Wine & Food KB', now());
insert into suppliers(name, created_at) values('Solo io', now());
insert into suppliers(name, created_at) values('Nordic Kiwi Brewers AB', now());
insert into suppliers(name, created_at) values('GL Brands AB', now());
insert into suppliers(name, created_at) values('Wine Brothers & Co', now());
insert into suppliers(name, created_at) values('Tirage AB', now());
insert into suppliers(name, created_at) values('MarBec AB', now());
insert into suppliers(name, created_at) values('Sibbetorps Gård AB', now());
insert into suppliers(name, created_at) values('Hönsinge Hantwerksbryggeri AB', now());
insert into suppliers(name, created_at) values('Södermännens Hantverksbryggeri AB', now());
insert into suppliers(name, created_at) values('Calwine AB', now());
insert into suppliers(name, created_at) values('Tegnér Spirits & Wine AB', now());
insert into suppliers(name, created_at) values('Sandahl International AB', now());
insert into suppliers(name, created_at) values('Swedish Wine Cellar AB', now());
insert into suppliers(name, created_at) values('Boucarou Wine & Dine AB', now());
insert into suppliers(name, created_at) values('Lowther & Partners AB', now());
insert into suppliers(name, created_at) values('Mora Bryggeri', now());
insert into suppliers(name, created_at) values('Kullabygdens Destilleri AB', now());
insert into suppliers(name, created_at) values('Olof af Wåhlberg', now());
insert into suppliers(name, created_at) values('AB InBev Sweden', now());
insert into suppliers(name, created_at) values('Vinolio AB', now());
insert into suppliers(name, created_at) values('Original Brands STHLM HB', now());
insert into suppliers(name, created_at) values('Sophronie AB', now());
insert into suppliers(name, created_at) values('Box Destilleri AB / High Coast', now());
insert into suppliers(name, created_at) values('Beerbliotek AB', now());
insert into suppliers(name, created_at) values('Torsöl Mikrobryggeri', now());
insert into suppliers(name, created_at) values('1413 Bryggkultur AB', now());
insert into suppliers(name, created_at) values('BarlindBeer AB', now());
insert into suppliers(name, created_at) values('Bearded Rabbit Brewery AB', now());
insert into suppliers(name, created_at) values('Bröderna Bommen AB', now());
insert into suppliers(name, created_at) values('Men Of Spirit AB', now());
insert into suppliers(name, created_at) values('House of Liquids', now());
insert into suppliers(name, created_at) values('Isles of Wines AB', now());
insert into suppliers(name, created_at) values('Sydamerikaviner AB', now());
insert into suppliers(name, created_at) values('Cavarosa Wine AB', now());
insert into suppliers(name, created_at) values('Prins Katts Hantverksöl', now());
insert into suppliers(name, created_at) values('MN Choklad AB', now());
insert into suppliers(name, created_at) values('Sysskonhem Bryggeri AB', now());
insert into suppliers(name, created_at) values('Skogh Development Design AB', now());
insert into suppliers(name, created_at) values('Mjelga Hantverksbryggeri', now());
insert into suppliers(name, created_at) values('Stockholms Bränneri AB', now());
insert into suppliers(name, created_at) values('Östgötaslättens produktion AB', now());
insert into suppliers(name, created_at) values('Foodspice', now());
insert into suppliers(name, created_at) values('Yolana Mode', now());
insert into suppliers(name, created_at) values('Barlingbo Bryggeri AB', now());
insert into suppliers(name, created_at) values('Gamla Hesselby Bryggeri AB', now());
insert into suppliers(name, created_at) values('Strandlida Hopspace AB', now());
insert into suppliers(name, created_at) values('LOMO International AB', now());
insert into suppliers(name, created_at) values('Runemount Scandinavia AB', now());
insert into suppliers(name, created_at) values('Argoria AB', now());
insert into suppliers(name, created_at) values('Champagnekällaren i Sverige AB', now());
insert into suppliers(name, created_at) values('Hernö Hantverksöl AB', now());
insert into suppliers(name, created_at) values('Margareta Laike', now());
insert into suppliers(name, created_at) values('Pine Bridge Brewery AB', now());
insert into suppliers(name, created_at) values('Revsunds Brewery AB', now());
insert into suppliers(name, created_at) values('Spike Brewery AB', now());
insert into suppliers(name, created_at) values('O.I.B AB', now());
insert into suppliers(name, created_at) values('Train Station Brewery AB', now());
insert into suppliers(name, created_at) values('Preuss International AB', now());
insert into suppliers(name, created_at) values('Svensk Absint AB', now());
insert into suppliers(name, created_at) values('Wessingekälla Brygghus AB', now());
insert into suppliers(name, created_at) values('Åhus 57:5 AB', now());
insert into suppliers(name, created_at) values('Ängöl AB', now());
insert into suppliers(name, created_at) values('Grand Labels AB', now());
insert into suppliers(name, created_at) values('Spirits of Passion AB', now());
insert into suppliers(name, created_at) values('Ahlén & Small Trading AB', now());
insert into suppliers(name, created_at) values('Mouette Swedish Wine Import', now());
insert into suppliers(name, created_at) values('Burgsviks Bryggeri AB', now());
insert into suppliers(name, created_at) values('Thompson Consulting & Trading', now());
insert into suppliers(name, created_at) values('Herdenstam Vinhandel', now());
insert into suppliers(name, created_at) values('House of Wine Georgia AB', now());
insert into suppliers(name, created_at) values('Wine Rebels HB', now());
insert into suppliers(name, created_at) values('Euskadi Wine & Spirits', now());
insert into suppliers(name, created_at) values('tottOvin', now());
insert into suppliers(name, created_at) values('Riktig Cider', now());
insert into suppliers(name, created_at) values('The Company of Urban wines&Other Liquids Sweden', now());
insert into suppliers(name, created_at) values('Taste of Mallorca AB', now());
insert into suppliers(name, created_at) values('Oppigårds Bryggeri AB', now());
insert into suppliers(name, created_at) values('Åkersberga Bryggeri AB', now());
insert into suppliers(name, created_at) values('Spruce Up AB', now());
insert into suppliers(name, created_at) values('Dykes Brewery AB', now());
insert into suppliers(name, created_at) values('Grästorps Bryggeri AB', now());
insert into suppliers(name, created_at) values('Teknikservice i Torrskog', now());
insert into suppliers(name, created_at) values('Hönöbryggeriet AB', now());
insert into suppliers(name, created_at) values('Bergslagens Brygghus AB', now());
insert into suppliers(name, created_at) values('Wine Trade Sweden AB', now());
insert into suppliers(name, created_at) values('Ybenets Wine AB', now());
insert into suppliers(name, created_at) values('Hops N Leon of Skaraborg AB', now());
insert into suppliers(name, created_at) values('Vin & Natur Malmö AB', now());
insert into suppliers(name, created_at) values('Uppsala Destilleri AB', now());
insert into suppliers(name, created_at) values('Kvarnagårdens Bryggeri AB', now());
insert into suppliers(name, created_at) values('Idlewild AB', now());
insert into suppliers(name, created_at) values('The Uncharted Brewing Company AB', now());
insert into suppliers(name, created_at) values('Sangiro AB', now());
insert into suppliers(name, created_at) values('Figeholms Bryggeri AB', now());
insert into suppliers(name, created_at) values('ÅBC Åredalens BryggCompagni AB', now());
insert into suppliers(name, created_at) values('Kullens Bryggeri AB', now());
insert into suppliers(name, created_at) values('Wine Selection, Amongré AB', now());
insert into suppliers(name, created_at) values('Gårdsbryggeriet 65°N', now());
insert into suppliers(name, created_at) values('Hop Shed Brewery AB', now());
insert into suppliers(name, created_at) values('Dryckesbutiken Timotejgatan AB', now());
insert into suppliers(name, created_at) values('Vattudalen Whisky Handelsbolag', now());
insert into suppliers(name, created_at) values('Tappers Bryggeri & Musteri AB', now());
insert into suppliers(name, created_at) values('Good Guys Brew AB', now());
insert into suppliers(name, created_at) values('Kornheddinge BryggeriKompani AB', now());
insert into suppliers(name, created_at) values('Josefin Lagerhorn', now());
insert into suppliers(name, created_at) values('Lockeby Bryggeri AB', now());
insert into suppliers(name, created_at) values('Hantverksbryggeriet AB', now());
insert into suppliers(name, created_at) values('Flädie Vinproduktion AB', now());
insert into suppliers(name, created_at) values('Tjers Bryggeri AB', now());
insert into suppliers(name, created_at) values('Gotland Whisky AB', now());
insert into suppliers(name, created_at) values('Norrlandsbryggarna AB', now());
insert into suppliers(name, created_at) values('Core Wine AB', now());
insert into suppliers(name, created_at) values('Hvellinge Spritfabriks AB', now());
insert into suppliers(name, created_at) values('Dryck STHLM Retail AB', now());
insert into suppliers(name, created_at) values('Wine Detectives AB', now());
insert into suppliers(name, created_at) values('Portofoliowines AB', now());
insert into suppliers(name, created_at) values('Hübsch Vinhandel AB', now());
insert into suppliers(name, created_at) values('Andalucia Wines', now());
insert into suppliers(name, created_at) values('Starkstrom Wineimport Limited UK', now());
insert into suppliers(name, created_at) values('Barrels and Kegs AB', now());
insert into suppliers(name, created_at) values('Engsdalens Vin AB', now());
insert into suppliers(name, created_at) values('Södra Stockholms Brygghus', now());
insert into suppliers(name, created_at) values('Vin Champagne Produits de France AB', now());
insert into suppliers(name, created_at) values('Freixenet Nordic AB', now());
insert into suppliers(name, created_at) values('Bra sprit i Sverige AB', now());
insert into suppliers(name, created_at) values('W&B of Sweden AB', now());
insert into suppliers(name, created_at) values('Havas & Co', now());
insert into suppliers(name, created_at) values('137:ans Beer & Spirits AB', now());
insert into suppliers(name, created_at) values('Bottenvikens bryggeri', now());
insert into suppliers(name, created_at) values('Aktiebolaget Nyckelbryggerier', now());
insert into suppliers(name, created_at) values('Billdale & Co AB', now());
insert into suppliers(name, created_at) values('Ryssby bryggeri', now());
insert into suppliers(name, created_at) values('Gammelbacka Bryggeri AB', now());
insert into suppliers(name, created_at) values('Håks Gård', now());
insert into suppliers(name, created_at) values('Inlands Bryggeri AB', now());
insert into suppliers(name, created_at) values('Möllys', now());
insert into suppliers(name, created_at) values('GustaVino AB', now());
insert into suppliers(name, created_at) values('Jemtehed & Brande AB', now());
insert into suppliers(name, created_at) values('Reinklou Bryggerier AB', now());
insert into suppliers(name, created_at) values('Beersmiths AB', now());
insert into suppliers(name, created_at) values('Marbäcks Bryggeri AB', now());
insert into suppliers(name, created_at) values('Kronhuset Trading AB', now());
insert into suppliers(name, created_at) values('Nynäshamns Ångbryggeri AB', now());
insert into suppliers(name, created_at) values('Umida Partners AB', now());
insert into suppliers(name, created_at) values('Papilles food & beverage AB', now());
insert into suppliers(name, created_at) values('VelvetBox AB', now());
insert into suppliers(name, created_at) values('Arcus WineBrands Sweden AB', now());
insert into suppliers(name, created_at) values('Bandol Import HB', now());
insert into suppliers(name, created_at) values('DiMalda AB', now());
insert into suppliers(name, created_at) values('APC China Trading AB', now());
insert into suppliers(name, created_at) values('VD Wines AB', now());
insert into suppliers(name, created_at) values('Din Mässpartner i Örebro', now());
insert into suppliers(name, created_at) values('Stallhagen AB Sverige Filial', now());
insert into suppliers(name, created_at) values('Wet Whistle Brewery AB', now());
insert into suppliers(name, created_at) values('Tempel Brygghus AB', now());
insert into suppliers(name, created_at) values('Lost Island Brewery AB', now());
insert into suppliers(name, created_at) values('Bryggeri Rosenhill AB', now());
insert into suppliers(name, created_at) values('Eskilstuna Ölkultur AB', now());
insert into suppliers(name, created_at) values('ProConWine AB', now());
insert into suppliers(name, created_at) values('Providential Wines & Spirits AB', now());
insert into suppliers(name, created_at) values('Carl Vin & Wine AB', now());
insert into suppliers(name, created_at) values('Träkumla Rom AB', now());
insert into suppliers(name, created_at) values('Johan Matsanders', now());
insert into suppliers(name, created_at) values('Mälardalens Frukt & Grönt i Västerås AB', now());
insert into suppliers(name, created_at) values('Wineshare Sweden Stig Calderon', now());
insert into suppliers(name, created_at) values('Noham Group AB', now());
insert into suppliers(name, created_at) values('AvecSweden AB', now());
insert into suppliers(name, created_at) values('Backafallsbyn AB', now());
insert into suppliers(name, created_at) values('Norbotnia Whisky HB', now());
insert into suppliers(name, created_at) values('Gastrodev Vin & Sprit AB', now());
insert into suppliers(name, created_at) values('Scala Wines Import AB', now());
insert into suppliers(name, created_at) values('GefleBockens Bryggeri AB', now());
insert into suppliers(name, created_at) values('Högberga Vinfabrik AB', now());
insert into suppliers(name, created_at) values('Björketorp Consulting AB', now());
insert into suppliers(name, created_at) values('UPP Brewing AB', now());
insert into suppliers(name, created_at) values('BSSK IMPEX AB', now());
insert into suppliers(name, created_at) values('Länna Bruk Dryckeshandel AB', now());
insert into suppliers(name, created_at) values('Selbo Consulting AB', now());
insert into suppliers(name, created_at) values('Bakalar AB', now());
insert into suppliers(name, created_at) values('Arvika bryggeri', now());
insert into suppliers(name, created_at) values('Stjernsund Brygghus AB', now());
insert into suppliers(name, created_at) values('Ottsjö Café AB', now());
insert into suppliers(name, created_at) values('Trosa Ölkompani AB', now());
insert into suppliers(name, created_at) values('Wine Mechanics AB', now());
insert into suppliers(name, created_at) values('Vareböke Bryggeri AB', now());
insert into suppliers(name, created_at) values('Sydamerikaviner HB', now());
insert into suppliers(name, created_at) values('SWSwine Köksinredarna Björkman Design AB', now());
insert into suppliers(name, created_at) values('Vinetum AB', now());
insert into suppliers(name, created_at) values('Enoterra AB', now());
insert into suppliers(name, created_at) values('Tjaerdalen Beer & Whisky AB', now());
insert into suppliers(name, created_at) values('Dryckesbolaget Gustav Vasa AB', now());
insert into suppliers(name, created_at) values('Bevalta AB', now());
insert into suppliers(name, created_at) values('P A Nilsson Vinhandel', now());
insert into suppliers(name, created_at) values('Aktiebolaget Old Road and Friends', now());
insert into suppliers(name, created_at) values('Två Feta Grisar AB', now());
insert into suppliers(name, created_at) values('Extra Mile HB', now());
insert into suppliers(name, created_at) values('Svartbergets Café & Restaurang AB', now());
insert into suppliers(name, created_at) values('Sad Robot Brewing AB', now());
insert into suppliers(name, created_at) values('Brewgineers AB', now());
insert into suppliers(name, created_at) values('Villovägens Bryggeri AB', now());
insert into suppliers(name, created_at) values('Stigbergets bryggeri AB', now());
insert into suppliers(name, created_at) values('AB Mohawk Brewing Company', now());
insert into suppliers(name, created_at) values('Mjödner AB', now());
insert into suppliers(name, created_at) values('Svenska Eldvatten AB', now());
insert into suppliers(name, created_at) values('Kollektivet Dryckeshandel AB', now());
insert into suppliers(name, created_at) values('Quid Vis Vin AB', now());
insert into suppliers(name, created_at) values('Krönleins', now());
insert into suppliers(name, created_at) values('Ms Winery AB', now());
insert into suppliers(name, created_at) values('Heba Food & Beverages AB', now());
insert into suppliers(name, created_at) values('Gusto Divino i Göteborg AB', now());
insert into suppliers(name, created_at) values('Top Note Wine AB', now());
insert into suppliers(name, created_at) values('Sebastian Jofre Armijo', now());
insert into suppliers(name, created_at) values('Uddevalla Bryggeri AB', now());
insert into suppliers(name, created_at) values('Agathos AB', now());
insert into suppliers(name, created_at) values('Rocket Brewing Company AB', now());
insert into suppliers(name, created_at) values('Arilds vingård AB', now());
insert into suppliers(name, created_at) values('Idunn Norsjö Wine & Co AB', now());
insert into suppliers(name, created_at) values('Fireside Inn AB', now());
insert into suppliers(name, created_at) values('Kyrkeby Bränneri AB', now());
insert into suppliers(name, created_at) values('Subbe Bryggeri AB', now());
insert into suppliers(name, created_at) values('Westerbottens Bryggeri AB', now());
insert into suppliers(name, created_at) values('Byaregårdens Brygghus HB', now());
insert into suppliers(name, created_at) values('Constant Companion AB', now());
insert into suppliers(name, created_at) values('Dervana AB', now());
insert into suppliers(name, created_at) values('Trollsås & Partners AB', now());
insert into suppliers(name, created_at) values('1423 Noble Spirit AB', now());
insert into suppliers(name, created_at) values('New Frontier Wines AB', now());
insert into suppliers(name, created_at) values('Pompette AB', now());
insert into suppliers(name, created_at) values('Långviks Krydderi & Handel', now());
insert into suppliers(name, created_at) values('Caves du Vineum i Sverige AB', now());
insert into suppliers(name, created_at) values('Ödåkra Brygghus AB', now());
insert into suppliers(name, created_at) values('Bedstekilde - Vin av äpplen AB', now());
insert into suppliers(name, created_at) values('Wine Stain AB', now());
insert into suppliers(name, created_at) values('Liyu Handel', now());
insert into suppliers(name, created_at) values('Brasstacks Brewing Company AB', now());
insert into suppliers(name, created_at) values('Almby Brewery', now());
insert into suppliers(name, created_at) values('Mälardalen Brewing Company', now());
insert into suppliers(name, created_at) values('Stockholms Vinhus AB', now());
insert into suppliers(name, created_at) values('Gardo & Morris AB', now());
insert into suppliers(name, created_at) values('Sakeman & Sakesson AB', now());
insert into suppliers(name, created_at) values('Akebono Unlimited AB', now());
insert into suppliers(name, created_at) values('Deliq AB', now());
insert into suppliers(name, created_at) values('Nordic Liquids AB', now());
insert into suppliers(name, created_at) values('Canwine HB', now());
insert into suppliers(name, created_at) values('Green Premium Wine Gardeproduction', now());
insert into suppliers(name, created_at) values('En halvpall AB', now());
insert into suppliers(name, created_at) values('Stålhammars drycker AB', now());
insert into suppliers(name, created_at) values('UniTrends AB', now());
insert into suppliers(name, created_at) values('Pilsnergubbarna i Ulricehamn AB', now());
insert into suppliers(name, created_at) values('Rudolf Pétillant AB', now());
insert into suppliers(name, created_at) values('Femtorp AB', now());
insert into suppliers(name, created_at) values('Conaxess Trade Sweden AB', now());
insert into suppliers(name, created_at) values('ChampagneHuset CH', now());
insert into suppliers(name, created_at) values('Beskows Drycker AB', now());
insert into suppliers(name, created_at) values('Grönsöö Säteri AB', now());
insert into suppliers(name, created_at) values('Maglehems Musteri AB', now());
insert into suppliers(name, created_at) values('Axel Oliver Wine', now());
insert into suppliers(name, created_at) values('Savino AB', now());
insert into suppliers(name, created_at) values('Obrini Beverage Company AB', now());
insert into suppliers(name, created_at) values('Pardon My French AB', now());
insert into suppliers(name, created_at) values('Frutoso International AB', now());
insert into suppliers(name, created_at) values('Staffan Ottosson', now());
insert into suppliers(name, created_at) values('Spishyllan AB', now());
insert into suppliers(name, created_at) values('Kiruna Bryggeri Aktiebolag', now());
insert into suppliers(name, created_at) values('Sthlm Brewing Co AB', now());
insert into suppliers(name, created_at) values('P Skoogs Vinhandel i Öresund AB', now());
insert into suppliers(name, created_at) values('Loopen Marin AB', now());
insert into suppliers(name, created_at) values('Råda Bubbel AB', now());
insert into suppliers(name, created_at) values('Stripabryggeriet AB', now());
insert into suppliers(name, created_at) values('Gardshol Wines AB', now());
insert into suppliers(name, created_at) values('Smaland Brewing AB', now());
insert into suppliers(name, created_at) values('Sommestad & Malmnäs AB', now());
insert into suppliers(name, created_at) values('Standout Brands AB', now());
insert into suppliers(name, created_at) values('Perpetuelle AB', now());
insert into suppliers(name, created_at) values('Chastel Beverage KB', now());
insert into suppliers(name, created_at) values('Golden Alco', now());
insert into suppliers(name, created_at) values('Belgodeli', now());
insert into suppliers(name, created_at) values('KallsaUtbildningsConsult', now());
insert into suppliers(name, created_at) values('Otto Suenson & Co AB', now());
insert into suppliers(name, created_at) values('Beerium Kraftölsbryggeri AB', now());
insert into suppliers(name, created_at) values('Meadgard AB', now());
insert into suppliers(name, created_at) values('Lundabryggeriet AB', now());
insert into suppliers(name, created_at) values('Strömsholms Brygghus', now());
insert into suppliers(name, created_at) values('European Wine & Beverage', now());
insert into suppliers(name, created_at) values('Fontana Food AB', now());
insert into suppliers(name, created_at) values('Bryggeri 1766', now());
insert into suppliers(name, created_at) values('Alafors Kvarnen i Anneberg Brygghus AB', now());
insert into suppliers(name, created_at) values('Kullabergs Vingård AB', now());
insert into suppliers(name, created_at) values('Veritabel Vin AB', now());
insert into suppliers(name, created_at) values('Keane Brewing AB', now());
insert into suppliers(name, created_at) values('Fermenterarna Bryggeri AB', now());
insert into suppliers(name, created_at) values('O/O Brewing AB', now());
insert into suppliers(name, created_at) values('Stockholm Wine Importers AB', now());
insert into suppliers(name, created_at) values('Scientific Lab Glass AB', now());
insert into suppliers(name, created_at) values('Bondi AB', now());
insert into suppliers(name, created_at) values('LXR Wines HB', now());
insert into suppliers(name, created_at) values('Norrlöf Nils Åke Patrik', now());
insert into suppliers(name, created_at) values('Södåkra Vingård HB', now());
insert into suppliers(name, created_at) values('Kustens Gårdsbryggeri AB', now());
insert into suppliers(name, created_at) values('Allsta Bryggeri', now());
insert into suppliers(name, created_at) values('Havsjö Delikatesser AB', now());
insert into suppliers(name, created_at) values('Lilla Ölfabriken PP AB', now());
insert into suppliers(name, created_at) values('Bustad Brewing AB', now());
insert into suppliers(name, created_at) values('Triplicity Brewing AB', now());
insert into suppliers(name, created_at) values('Gute Vingård AB', now());
insert into suppliers(name, created_at) values('Säbyholms Bryggeri AB', now());
insert into suppliers(name, created_at) values('Fermenteriet AB', now());
insert into suppliers(name, created_at) values('Orsholms Brygghus AB', now());
insert into suppliers(name, created_at) values('Per Knutsson Vistakullefruktodling', now());
insert into suppliers(name, created_at) values('Red & White AB', now());
insert into suppliers(name, created_at) values('ICS Trading HB', now());
insert into suppliers(name, created_at) values('Renards Import AB', now());
insert into suppliers(name, created_at) values('Brasri AB', now());
insert into suppliers(name, created_at) values('Hopsan Brewing AB', now());
insert into suppliers(name, created_at) values('Vin Drumlin AB', now());
insert into suppliers(name, created_at) values('AB No.1 Production', now());
insert into suppliers(name, created_at) values('Vinitor AB', now());
insert into suppliers(name, created_at) values('Agrell & Hartley Selection AB', now());
insert into suppliers(name, created_at) values('Beverage Market of Scandinavia AB', now());
insert into suppliers(name, created_at) values('RajRaj Bryggeri AB', now());
insert into suppliers(name, created_at) values('Suttungs Bryggeri', now());
insert into suppliers(name, created_at) values('Niscada International AB', now());
insert into suppliers(name, created_at) values('Köpings Musteri AB', now());
insert into suppliers(name, created_at) values('Jämmerdalen Hantverksbryggeri Handelsbolag', now());
insert into suppliers(name, created_at) values('Kaj Nilsson', now());
insert into suppliers(name, created_at) values('Bier & Co Sweden AB', now());
insert into suppliers(name, created_at) values('Philipson Söderberg AB', now());
insert into suppliers(name, created_at) values('Wine Waves', now());
insert into suppliers(name, created_at) values('Beer & Spiritpartners Nordic AB', now());
insert into suppliers(name, created_at) values('Allegresse AB', now());
insert into suppliers(name, created_at) values('Northern Beverages AB', now());
insert into suppliers(name, created_at) values('Sparkling collection by J&M AB', now());
insert into suppliers(name, created_at) values('Panache Sweden AB', now());
insert into suppliers(name, created_at) values('Portucastas AB', now());
insert into suppliers(name, created_at) values('Jack Barlows Wine AB', now());
insert into suppliers(name, created_at) values('NBI i Växjö AB', now());
insert into suppliers(name, created_at) values('Bryggeriet Stenhammaren AB', now());
insert into suppliers(name, created_at) values('Winberg & Partner AB', now());
insert into suppliers(name, created_at) values('KronUgglan Handelsbolag', now());
insert into suppliers(name, created_at) values('Snausarve Gårdsbryggeri AB', now());
insert into suppliers(name, created_at) values('Fredholms Vin', now());
insert into suppliers(name, created_at) values('Business Monkey Brewing AB', now());
insert into suppliers(name, created_at) values('Scanwine of Sweden AB', now());
insert into suppliers(name, created_at) values('Svanshals Brygghus AB', now());
insert into suppliers(name, created_at) values('Sam & Jenny Wine & Food', now());
insert into suppliers(name, created_at) values('Caffe Olivedal AB', now());
insert into suppliers(name, created_at) values('Husaren Bryggeri Aktiebolag', now());
insert into suppliers(name, created_at) values('Selected Malts Barkevall Westerberg AB', now());
insert into suppliers(name, created_at) values('Lucky Ones Wines and Beers Import HB', now());
insert into suppliers(name, created_at) values('Words & Wines AB', now());
insert into suppliers(name, created_at) values('Åhus Bryggeri Anno 1900', now());
insert into suppliers(name, created_at) values('Bråhovda Drinks AB', now());
insert into suppliers(name, created_at) values('Malmö Brewing AB', now());
insert into suppliers(name, created_at) values('Sollentuna Bryggeri', now());
insert into suppliers(name, created_at) values('En Aleigen Brewery', now());
insert into suppliers(name, created_at) values('Cedentolin AB', now());
insert into suppliers(name, created_at) values('Västergården Bryggeri AB', now());
insert into suppliers(name, created_at) values('Wittja Brygghus AB', now());
insert into suppliers(name, created_at) values('The Wine Collection Sweden Holding AB', now());
insert into suppliers(name, created_at) values('Agent Clay AB', now());
insert into suppliers(name, created_at) values('Neptunium AB', now());
insert into suppliers(name, created_at) values('Olito Vin Handelsbolag', now());
insert into suppliers(name, created_at) values('The Odd House Brewing Company AB', now());
insert into suppliers(name, created_at) values('Brooklyn Stockholm OpCo AB', now());
insert into suppliers(name, created_at) values('Dryck STHLM AB', now());
insert into suppliers(name, created_at) values('Smögen Whisky AB', now());
insert into suppliers(name, created_at) values('Backman Vinhandel AB', now());
insert into suppliers(name, created_at) values('Amazing Wines Hedberg & Wising AB', now());
insert into suppliers(name, created_at) values('PR Trot & Trade AB', now());
insert into suppliers(name, created_at) values('Norrlands Fruktvin AB', now());
insert into suppliers(name, created_at) values('Varberg Beerworks AB', now());
insert into suppliers(name, created_at) values('1868 Group AB', now());
insert into suppliers(name, created_at) values('Handelsbolaget Guideline Wines', now());
insert into suppliers(name, created_at) values('Johan Hagström & Co HAB', now());
insert into suppliers(name, created_at) values('Baccus Vinhandel i Mora AB', now());
insert into suppliers(name, created_at) values('Hydmar AB', now());
insert into suppliers(name, created_at) values('Scandinavian Hub AB', now());
insert into suppliers(name, created_at) values('Distillery & Spirits of Lapland AB', now());
insert into suppliers(name, created_at) values('H.A.R.R.E.L AB', now());
insert into suppliers(name, created_at) values('Sweden Spirit Group AB', now());
insert into suppliers(name, created_at) values('Säröbanans Bryggeri AB', now());
insert into suppliers(name, created_at) values('DaiFratelliWine AB', now());
insert into suppliers(name, created_at) values('Hybris AB', now());
insert into suppliers(name, created_at) values('Gröna Linjen Bryggeri AB', now());
insert into suppliers(name, created_at) values('Norrbottens Destilleri AB', now());
insert into suppliers(name, created_at) values('Prodedge Filial', now());
insert into suppliers(name, created_at) values('AB Östersjö Vodka', now());
insert into suppliers(name, created_at) values('Nordic Beverage Company AB', now());
insert into suppliers(name, created_at) values('Stallarholmens brygghus AB', now());
insert into suppliers(name, created_at) values('Spriteriet AB', now());
insert into suppliers(name, created_at) values('Qvarnens AB', now());
insert into suppliers(name, created_at) values('Två Liljor AB', now());
insert into suppliers(name, created_at) values('Brygg3an i Halmstad AB', now());
insert into suppliers(name, created_at) values('The Piraya Brewery AB', now());
insert into suppliers(name, created_at) values('Vilda Bryggeri AB', now());
insert into suppliers(name, created_at) values('Berners Mat och Vinklubb AB', now());
insert into suppliers(name, created_at) values('Rospart Holding AB', now());
insert into suppliers(name, created_at) values('Sour & Wine AB', now());
insert into suppliers(name, created_at) values('Arbore Ab', now());
insert into suppliers(name, created_at) values('Hoff Vinhandel AB', now());
insert into suppliers(name, created_at) values('Invini AB', now());
insert into suppliers(name, created_at) values('Ceylon Wines & Co. AB', now());
insert into suppliers(name, created_at) values('Klocktornet Destilleri AB', now());
insert into suppliers(name, created_at) values('Björknäs Bryggeri AB', now());
insert into suppliers(name, created_at) values('Sincere Wines AB', now());
insert into suppliers(name, created_at) values('Taste Port Gothenburg AB', now());
insert into suppliers(name, created_at) values('Wine4U i Finspång AB', now());
insert into suppliers(name, created_at) values('Wine Shack AB', now());
insert into suppliers(name, created_at) values('SAV Winery AB (publ)', now());
insert into suppliers(name, created_at) values('Aktiebolaget Occivins', now());
insert into suppliers(name, created_at) values('Rosforth & Rosforth AB', now());
insert into suppliers(name, created_at) values('WineTastic Sweden AB', now());
insert into suppliers(name, created_at) values('Exoro Wine Import AB', now());
insert into suppliers(name, created_at) values('Acid Wines Stockholm Handelsbolag', now());
insert into suppliers(name, created_at) values('WeBrew Brewing AB', now());
insert into suppliers(name, created_at) values('Elisa Vin AB', now());
insert into suppliers(name, created_at) values('Tjärnsjö Brewery', now());
insert into suppliers(name, created_at) values('Glabo Gårdsbryggeri AB', now());
insert into suppliers(name, created_at) values('Exermans Bryggeri', now());
insert into suppliers(name, created_at) values('Viboe Bryggeri AB', now());
insert into suppliers(name, created_at) values('Kesuddens Konsult AB', now());
insert into suppliers(name, created_at) values('Vinkollektivet AB', now());
insert into suppliers(name, created_at) values('Två Små Svin/Nygren Catering & Event HB', now());
insert into suppliers(name, created_at) values('Hernö Gin AB', now());
insert into suppliers(name, created_at) values('Skogens Sköna Gröna AB', now());
insert into suppliers(name, created_at) values('Lakeside Brewery', now());
insert into suppliers(name, created_at) values('Hawelkas Brewing Company AB', now());
insert into suppliers(name, created_at) values('Wilderness Brewery AB', now());
insert into suppliers(name, created_at) values('Illbatting Brewing HB', now());
insert into suppliers(name, created_at) values('Vinolin AB', now());
insert into suppliers(name, created_at) values('Nova Handel i Göteborg AB', now());
insert into suppliers(name, created_at) values('Hellström Gin AB', now());
insert into suppliers(name, created_at) values('I.C.E Vodka of Sweden AB', now());
insert into suppliers(name, created_at) values('OM.DuoVin AB', now());
insert into suppliers(name, created_at) values('KON Beverages AB', now());
insert into suppliers(name, created_at) values('S by Jorge', now());
insert into suppliers(name, created_at) values('Bevono Beverages AB', now());
insert into suppliers(name, created_at) values('Lydén Distillery AB', now());
insert into suppliers(name, created_at) values('Raïm vinimport handelsbolag', now());
insert into suppliers(name, created_at) values('Unibärsum AB', now());
insert into suppliers(name, created_at) values('Vuxenpedagogisk Konsultation i Linköping AB', now());
insert into suppliers(name, created_at) values('Frillestads Vingård HB', now());
insert into suppliers(name, created_at) values('Pilsnerimporten Englesson och Axen AB', now());
insert into suppliers(name, created_at) values('Nordisk Drama & Dokumentär AB', now());
insert into suppliers(name, created_at) values('None', now());
insert into suppliers(name, created_at) values('BrewOre AB', now());
insert into suppliers(name, created_at) values('Sodafactory Stockholm AB', now());
insert into suppliers(name, created_at) values('Yellow Eye Spirits AB', now());
insert into suppliers(name, created_at) values('ALWines Sweden AB', now());
insert into suppliers(name, created_at) values('RekoVin Sverige AB', now());
insert into suppliers(name, created_at) values('Blomdell C&M AB', now());
insert into suppliers(name, created_at) values('JAGA Solutions AB', now());
insert into suppliers(name, created_at) values('Segerstrom Wines AB', now());
insert into suppliers(name, created_at) values('Avenue wines AB', now());
insert into suppliers(name, created_at) values('Köpingsbergs Gård AB', now());
insert into suppliers(name, created_at) values('Home Studio Revsund HB', now());
insert into suppliers(name, created_at) values('AB Wolkes Punsch', now());
insert into suppliers(name, created_at) values('Jönköpings Bryggeri AB', now());
insert into suppliers(name, created_at) values('Tumi AB', now());
insert into suppliers(name, created_at) values('Cesarino Gobbi', now());
insert into suppliers(name, created_at) values('Heavy MetAle AB', now());
insert into suppliers(name, created_at) values('Skebo Bruksbryggeri ekonomisk förening', now());
insert into suppliers(name, created_at) values('H3 Systems AB', now());
insert into suppliers(name, created_at) values('Plivit Trade AB', now());
insert into suppliers(name, created_at) values('Gripsholm Distillery AB', now());
insert into suppliers(name, created_at) values('China Trading i Stockholm AB', now());
insert into suppliers(name, created_at) values('Aktiebolaget Mat & Dryck i Stockholm', now());
insert into suppliers(name, created_at) values('Lindvino', now());
insert into suppliers(name, created_at) values('Just Brands in Sweden AB', now());
insert into suppliers(name, created_at) values('Gullyckevin och konsult', now());
insert into suppliers(name, created_at) values('Särtshöga Vingård AB', now());
insert into suppliers(name, created_at) values('Holavedens Handel Hus Ek för', now());
insert into suppliers(name, created_at) values('Mercura Sweden AB', now());
insert into suppliers(name, created_at) values('Stragas-Gruppen AB', now());
insert into suppliers(name, created_at) values('Shotluckan Holding AB', now());
insert into suppliers(name, created_at) values('WSB The Beverage Company AB', now());
insert into suppliers(name, created_at) values('UNIQ Handelsbolag', now());
insert into suppliers(name, created_at) values('Pr. Estige Spirits AB', now());
insert into suppliers(name, created_at) values('ZNAPS Sweden AB', now());
insert into suppliers(name, created_at) values('Urban Beverages AB', now());
insert into suppliers(name, created_at) values('Magnum Wine AB', now());
insert into suppliers(name, created_at) values('Ribes Nigrum Vingård AB', now());
insert into suppliers(name, created_at) values('Solsidans Bryggeri AB', now());
insert into suppliers(name, created_at) values('Ekjord Sweden AB', now());
insert into suppliers(name, created_at) values('Supreme Wine & Spirit AB', now());
insert into suppliers(name, created_at) values('Vinum Veritas Wine Agency AB', now());
insert into suppliers(name, created_at) values('Sörby Vinhandel AB', now());
insert into suppliers(name, created_at) values('Stora Bryne Vin & Trädgård', now());
insert into suppliers(name, created_at) values('C & E Gastro-Import AB', now());
insert into suppliers(name, created_at) values('Adelsö Bryggeri AB', now());
insert into suppliers(name, created_at) values('CHill Creek AB', now());
insert into suppliers(name, created_at) values('Georg Strömfelt', now());
insert into suppliers(name, created_at) values('Carlberg Vinhus AB', now());
insert into suppliers(name, created_at) values('Toivio Innovation AB', now());
insert into suppliers(name, created_at) values('Karl Källander', now());
insert into suppliers(name, created_at) values('Habibi Stockholm AB', now());
insert into suppliers(name, created_at) values('Mestej', now());
insert into suppliers(name, created_at) values('FC Bryggeri AB', now());
insert into suppliers(name, created_at) values('Mats Carlsson Reklambyrå Nordic Wine Company', now());
insert into suppliers(name, created_at) values('Gute Bryggeri', now());
insert into suppliers(name, created_at) values('Vinupplevelser i Sverige AB', now());
insert into suppliers(name, created_at) values('Österlenvin HB', now());
insert into suppliers(name, created_at) values('New Brews Sweden AB', now());
insert into suppliers(name, created_at) values('Classic Wine Sweden AB', now());
insert into suppliers(name, created_at) values('Dunder & Krut AB', now());
insert into suppliers(name, created_at) values('Modern Wines Sweden AB', now());
insert into suppliers(name, created_at) values('Sundell Selections AB', now());
insert into suppliers(name, created_at) values('Nygrens Hyrservice', now());
insert into suppliers(name, created_at) values('Bevgru AB', now());
insert into suppliers(name, created_at) values('Vinumlux', now());
insert into suppliers(name, created_at) values('SSARK Maltbryggeri AB', now());
insert into suppliers(name, created_at) values('Vinlusen AB', now());
insert into suppliers(name, created_at) values('Aktiebolaget Gbg Soda', now());
insert into suppliers(name, created_at) values('Laitilan Svenska Filial', now());
